### ISSUE TITLE
How to param date range in select field

### ISSUE THREAD

**Issue by vFourcade** [Sylius/Sylius-Standard#102]
Hi everybody 

i'm trying to enlarge date range in select field in Sylius
we can only select date between 2011 and 2021 
I need to set some date to 2009 or 2008 

How I can do this ?

Thank's a lot 👍

**Comment by michalmarcinkowski** [comment]
About which select are you asking?

**Comment by vFourcade** [comment]
Hi Michal

i'm asking about all date input field in backend
for exemple:
- product edit page with avaible date 

![date_1](https://cloud.githubusercontent.com/assets/19576114/15923901/c38a9fe0-2e2f-11e6-9e26-368d63a66e4e.png)

- i add date attribute to my product definition

![date_2](https://cloud.githubusercontent.com/assets/19576114/15923915/cf61a5c0-2e2f-11e6-9874-01fe0c7894da.png)
 
thank's for your help 👍

**Comment by michalmarcinkowski** [comment]
Closing as the old admin panel is gone.
