### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by CRTX** [Sylius/Sylius-Standard#103]
I see a recent Sylius commit that most likely addresses this issue:

https://github.com/Sylius/Sylius/pull/5256

I used the `php composer.phar create-project sylius/sylius-standard` command to install Sylius...

However this doesn't seem to include the recent bugfix. How can create a project with that bugflix included?

**Comment by tchapi** [comment]
+1 
And I guess some new commits in Sylius/Sylius might help this repo's stability. Any chance we can get an update on this repo ? 

Thanks !

**Comment by coox** [comment]
+1
Oh yes this fix landing in Sylius-Standard would be great!

**Comment by pamil** [comment]
`composer create-project -s dev sylius/sylius-standard` will install the development (unstable) version with that fix. If you do want stability, waiting for next release will be the best option.
