### ISSUE TITLE
Error Invalid credentials - every trying

### ISSUE THREAD

**Issue by maiskiykot** [Sylius/Sylius-Standard#1078]
I installed Sylius 1.14, added migrations, added fixtures. Added admin-user from bin/console. But all users not have login in admin area. 
"Error Invalid credentials - every trying". Why??? Anybody installed  Sylius  less than week? I trying second week!

**Comment by maiskiykot** [comment]
$argon2i$v=19$m=65536,t=4,p=1$eDJMUDRGRkxZczdocnMxSA$LIp1xfVqPzn2MeQ7nzCsSxj+r46ueaZ9puECl4kkF2o  - may be it is problem? I think password must be save by another way

**Comment by diimpp** [comment]
Hi @maiskiykot, I didn't try to install sylius-standard recently, but join our slack https://sylius.com/slack for support requests -- it would be easier to debug in real time chat.

**Comment by maiskiykot** [comment]
> Hi @maiskiykot, I didn't try to install sylius-standard recently, but join our slack https://sylius.com/slack for support requests -- it would be easier to debug in real time chat.

Thanks! It not resolving my problem

**Comment by maiskiykot** [comment]
I solved my problem! On my server used php 8.2. I placed php 8.1 and authorization was repaired! I think documentation may be more full.

**Comment by GSadee** [comment]
I'm closing as the problem has been solved.
