### ISSUE TITLE
Install problem: child node "security" at path "payum" must be configured

### ISSUE THREAD

**Issue by krewmarco** [Sylius/Sylius-Standard#11]
after running:
php composer.phar create-project sylius\sylius-standard -s dev sylius-standard
I get:

sylius.currency (EUR): USD
sylius.cache (file_system): 
                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "security" at path "payum" must be configured.                  
                                                                                 
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

**Comment by michalmarcinkowski** [comment]
Fixed.
