### ISSUE TITLE
No release of v0.19.0

### ISSUE THREAD

**Issue by krafas** [Sylius/Sylius-Standard#112]
Sylius released v0.19.0 on Jul 6, but there is still no Sylius-Standard release with that tag.

**Comment by ulisse73** [comment]
I believe the dev-master, because I symply invoked the command suggested by the official doc:

 composer.phar create-project sylius/sylius-standard -s dev

**Comment by ulisse73** [comment]
I read that the 0.19.0 version of Sylius require "^5.6" minimum version (because pamil/phpspec-generator-extension v0.3.0 requires php ^5.6).
Is it a way to install the platform on a 5.5.9 php version?

**Comment by pamil** [comment]
Sylius >=0.19 requires PHP 5.6 - that extension is only used in require-dev and specs, but the codebase itself may require features / fixes from PHP 5.6. You can use `--ignore-platform-reqs` and install it anyway, but it's on your own risk.

**Comment by ulisse73** [comment]
I understand. Thanks pamil!

**Comment by ulisse73** [comment]
Anyway, also the Sylius 0.19.0 version (NOT Sylius-Standard!) doesn't have the same look and feel as the demo one.
What's the right version to obtain THIS L&F? :-)
http://demo.sylius.org/admin/login

**Comment by ibasaw** [comment]
When i try to update to 0.19, got this error:

    Fatal error: Class 'Sylius\Bundle\CoreBundle\Kernel\Kernel' not found in /var/www/sources/xxx/app/AppKernel.php on line 9
