### ISSUE TITLE
Why the Sylius-Standard look and feel is not equal to demo one?

### ISSUE THREAD

**Issue by ulisse73** [Sylius/Sylius-Standard#114]
Hi to all,
I downloaded the current sylius standard project, but its look and feel is not the same as the one shown in the demo version:
http://demo.sylius.org/admin/login

How can I obtain a project indentical to the demo one?

Thanks in advance.

**Comment by krafas** [comment]
Did you download `dev-master` or `v0.18.0` version? There is quite big gap between versions, the `v0.19.0` tag is still missing (issue #112) at the Sylius-Standard.

**Comment by ulisse73** [comment]
I believe the dev-master, because I simply invoked the command suggested by the official doc:

composer.phar create-project sylius/sylius-standard -s dev

**Comment by michalmarcinkowski** [comment]
We will keep the demo updated to the latest version. Look forward to update this week!

**Comment by zacbrac** [comment]
Hi, did this ever get updated? I followed the basic instructions on http://sylius.org/download and end up with an older looking version.

**Comment by pjedrzejewski** [comment]
@zacbrac Yes, it is updated. Did you use -s beta according to the instruction?

**Comment by zacbrac** [comment]
@pjedrzejewski Yes I did, thank you for your quick reply.
