### ISSUE TITLE
Activate "bulk delete" action in Sylius (multiple delete)

### ISSUE THREAD

**Issue by ulisse73** [Sylius/Sylius-Standard#116]
Hi guys,
is there a way to enable in Sylius the "bulk delete", in other words, the ability to delete multiple rows in a resource list? (To have a list with checkboxes and a unique "Delete" button).

Thanks.

**Comment by michalmarcinkowski** [comment]
There is no "bulk delete" feature implemented OOTB yet. You would have to implement it on your own. Closing this as for support please use stackoverflow and ask question under "sylius" tag. 

We would happily accept a PR with this feature, if you're willing to implement it to Core, please open a feature request on https://github.com/Sylius/Sylius repo.
