### ISSUE TITLE
What are default admin credentials?

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius-Standard#117]
http://docs.sylius.org/en/latest/book/installation.html#accessing-the-administration-panel

> Have a look at the /admin url, where you will find the administration panel. Remember that you have to be logged in as an administrator using the credentials provided while installing Sylius.

I did not provide any credentials while installing

(just data for parameters.yml)

**Comment by christiankasse** [comment]
can I have the default login after installation to access the admin?

when i try to go to` localhost:8000/admin` I am redirected to `/ login` where I pass sylius whith password, I am denied access saying ERROR Bad credentials.
