### ISSUE TITLE
admin credentials provided during installation ineffective

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius-Standard#118]
admin credentials provided during installation and entered in:
`http://127.0.0.1:8000/admin`
display:

> Error. Invalid credentials.

SELECT * FROM `sylius_admin_user` show my user with column roles containinig

> a:1:{i:0;s:9:"ROLE_USER";}

**Comment by sruj** [comment]
---------------------------------
I'm not sure sentence from [installation Book ](http://docs.sylius.org/en/latest/book/installation.html#accessing-the-administration-panel) is correct

> Have a look at the /admin url, where you will find the administration panel.

maybe it should be info to first log in at `/admin/login` because url `/admin` redirect to `/login` but here i can't log in as administrator.

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
