### ISSUE TITLE
API Access denied for admin

### ISSUE THREAD

**Issue by mozzymoz** [Sylius/Sylius-Standard#119]
Hi there,

I followed the documentation on reaching the API.
Here is what I did:
1. Install Sylius `composer create-project -d sylius/sylius-standard`
2. `app/console sylius:install` entered my admin credentials
3. Logged into admin area (successfull)
4. Created API Client via `app/console sylius:oauth-server:create-client` and enabled all grant types ("password", "refresh_token", "token")
5. Curled `/api/oauth/v2/token` with client_id, client_secret, username and password
6. GET `/api/products` with obtained token in (curl -H "Authorization: Bearer [...]")

What do I get as a response from 6?

```
{"code":403,"message":"Access Denied."}
```

I can't seem to figure out how to access the API :/

**Comment by mozzymoz** [comment]
I checked the database and here are the entries from sylius_admin_user:

```
*************************** 1. row ***************************
                      id: 1
                username: John Doe
      username_canonical: john doe
                 enabled: 1
                    salt: e518kje1mjkgc0s4o0s0s4wss8g08w
                password: Km8xCpA3XGu3E24Z/7Q6TKsgQ5bAsnGngihLibIaLu434H/Ksjqs1IQMOr16RtEx79gpmEaBGVO8uDVKpE0CbQ==
              last_login: NULL
    password_reset_token: NULL
   password_requested_at: NULL
email_verification_token: NULL
             verified_at: NULL
                  locked: 0
              expires_at: NULL
   credentials_expire_at: NULL
                   roles: a:2:{i:0;s:9:"ROLE_USER";i:1;s:26:"ROLE_ADMINISTRATION_ACCESS";}
                   email: sylius@example.com
         email_canonical: sylius@example.com
              created_at: 2016-09-14 15:09:33
              updated_at: 2016-09-14 15:09:33
*************************** 2. row ***************************
                      id: 2
                username: Luke Brushwood
      username_canonical: luke brushwood
                 enabled: 1
                    salt: sjjr05v2200goockcc84k84swco0w8c
                password: b1DDDk7AsJb2plPKAFRbqV1VznoOfpqksD0lfbG/sDP+PjO5JxWjA6GZNfkquWrbnFykRxJXZkCiSwbXODH4PQ==
              last_login: NULL
    password_reset_token: NULL
   password_requested_at: NULL
email_verification_token: NULL
             verified_at: NULL
                  locked: 0
              expires_at: NULL
   credentials_expire_at: NULL
                   roles: a:3:{i:0;s:9:"ROLE_USER";i:1;s:26:"ROLE_ADMINISTRATION_ACCESS";i:2;s:15:"ROLE_API_ACCESS";}
                   email: api@example.com
         email_canonical: api@example.com
              created_at: 2016-09-14 15:09:33
              updated_at: 2016-09-14 15:09:33
*************************** 3. row ***************************
                      id: 3
                username: NULL
      username_canonical: NULL
                 enabled: 1
                    salt: rksa2dxenaosk4s8kg0g4wc4co0sws0
                password: 5y2yE0PhRq2fga0i4HqSYjX1pytf8i8QrEBO5T2SZEHfOlBrG+SclJvSqDKDjkakjdXQH45CUkASQ9bTnKdHhA==
              last_login: 2016-09-14 15:30:36
    password_reset_token: NULL
   password_requested_at: NULL
email_verification_token: NULL
             verified_at: NULL
                  locked: 0
              expires_at: NULL
   credentials_expire_at: NULL
                   roles: a:1:{i:0;s:9:"ROLE_USER";}
                   email: k[snip]de
         email_canonical: k[snip]de
              created_at: 2016-09-14 15:09:59
              updated_at: 2016-09-14 15:30:36
```

Seems like the installation failed to assigned the admin roles to my newly created user.

**Comment by mozzymoz** [comment]
Trying to promote my user using `app/console sylius:user:promote` did not work either, it could not even find my user

**Comment by lchrusciel** [comment]
If the message from the first post is correct, then the problem is with authorization token... You should remove colon after `Bearer`
` (curl -H "Authorization: Bearer: [...]")` -->  `(curl -H "Authorization: Bearer [...]")`

**Comment by mozzymoz** [comment]
Sorry my example above was wrong. I corrected it. It was sent without the colon, otherwise it would result in a different response:
```
{"error":"access_denied","error_description":"OAuth2 authentication required"}
```

**Comment by mozzymoz** [comment]
I just tried the same thing with the sylius@example.com user, but it also ended up in a `{"code":403,"message":"Access Denied."}`.

**Comment by lchrusciel** [comment]
Probably security is misconfigured. We will have to check it

**Comment by michalmarcinkowski** [comment]
Please follow the [docs](http://docs.sylius.org/en/latest/api/authorization.html) and everything will work.

**Comment by Dragony** [comment]
For anyone that might find this issue via Google: In my case the user did not have the required "ROLE_API_ACCESS" role in order to access the API resources. Using an access_token for sylius@example.com (as mentioned above) will not work, because that user does not have the role by default. You need to promote the user for this example to work.

**Comment by lchrusciel** [comment]
@Dragony or use api@example.com as a user. Password stays the same (`sylius`)

**Comment by bjrnblm** [comment]
@lchrusciel `sylius` as a password did not work for me, but `sylius-api` did.

**Comment by lchrusciel** [comment]
Bjorn, you are totally right! https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml#L111

My bad!

**Comment by lecajer** [comment]
This solved the issue in my setup. Grant the defaut user `ROLE_API_ACCESS` so we it can call endpoints `/api/v2/admin/*`
```sh
bin/console sylius:user:promote sylius@example.com ROLE_API_ACCESS --user-type=admin
```

**Comment by ebuildy** [comment]
I dont understand, Sylius says admin RBAC is a Sylius plus feature:

https://store.sylius.com/products/role-based-accesscontrol-plugin-by-sylius

But there is RBAC in free version too?
