### ISSUE TITLE
Composer install ends with warning

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius-Standard#123]
Doing `composer create-project -s dev sylius/sylius-standard`, after you set your configuration params, the process ends outputting 

```
! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.  


 [OK] All assets were successfully installed.                                                                           


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
Class Symfony\Cmf\Bundle\CreateBundle\Composer\ScriptHandler is not autoloadable, can not call post-install-cmd script
```

**Comment by nietzcheson** [comment]
@crevillo It is not memory in your virtual machine? This happened to me. I upgraded to 4G and works well ...

**Comment by crevillo** [comment]
I don't think so. But i'll try it. To me is more like a deps issue or
something. For instance, if you clone sylius master and do composer install
no warning appears.
Is only when you install sylius-standard following doc instructions.

**Comment by gorkalaucirica** [comment]
This seems fixed, no cmf related warning when installing using `composer create-project -s alpha`
