### ISSUE TITLE
Composer update fails

### ISSUE THREAD

**Issue by dszwcz** [Sylius/Sylius-Standard#126]
The installation proceeds without a problem (because composer.lock). When I try to make composer update the following problems arise:

1. After the attempt to execute post update clearing cache command I receive a message: `[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                       
  You have requested a non-existent service "FOSOAuthServerBundle must be registered in kernel."`

2. So I add a FOSOAuthServer bundle to AppKernel and then I see another error: `Class "model" is not configured for resource "sylius.api_user"`. ApiBundle/Resources/config/app/config.yml file should be included.

3. [NEW] In the `app/config/security.yml` config file `sylius.admin_user.provider.email_or_name_based` should be replaced by `sylius.admin_user_provider.email_or_name_based`.

[PR](https://github.com/Sylius/Sylius-Standard/pull/127) where FOSOAuthServerBundle added to the kernel.
Should I update composer.lock too?

**Comment by dszwcz** [comment]
[PR](https://github.com/Sylius/Sylius-Standard/pull/127) where FOSOAuthServerBundle added to the kernel.

**Comment by lchrusciel** [comment]
The second problem could be resolved by adding the following line to config file:
```yml
imports:
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yml" }
```

**Comment by krisElphenor** [comment]
Hello,

I did the same update and encountered the same errors, so i applied the above fixes (added FOSOAuthServerBundle to the kernel and the SyliusApiBundle config.yml to the config file).

Now, i have the following error:
`The service "security.authentication.manager" has a dependency on a non-existent service "sylius.admin_user.provider.email_or_name_based".`

Did anyone else has the same issue ? or any idea about what i did miss ?

Thanks

**Comment by dszwcz** [comment]
@krisElphenor open the `app/config/security.yml` config file and change sylius.admin_user.provider.email_or_name_based to sylius.admin_user_provider.email_or_name_based

**Comment by dszwcz** [comment]
Closed because all this is solved by @Zales0123

**Comment by krisElphenor** [comment]
Thanks @dszwcz , i did checked that file on github, but didn't notice it has changed.

Also, i would like to point out, the next error is:
`The service "security.firewall.map.context.shop" has a dependency on a non-existent service "sylius.authenticaiton.success_handler".`

it's just a spelling mistake, it should be 
`The service "security.firewall.map.context.shop" has a dependency on a non-existent service "sylius.authentication.success_handler".`

...just in case it might help somebody else.
