### ISSUE TITLE
#Locale - Not function in all modules

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius-Standard#129]
I created a new **Locale**:

![locale](https://cloud.githubusercontent.com/assets/1699198/19357519/ad2f45a0-9137-11e6-8d9a-007a2192d805.png)

This does not work in the modules where this is required. Does not appear:

![methodpayment](https://cloud.githubusercontent.com/assets/1699198/19357615/0b6357ba-9138-11e6-8451-d5b51a6098ca.png)

I tried with sylius/sylius and in this bundle does work:

![new payment method](https://cloud.githubusercontent.com/assets/1699198/19357698/57bca076-9138-11e6-822a-9141e5f7c906.png)

Any solution?

**Comment by michalmarcinkowski** [comment]
Sylius Standard will be updated to the newest `sylius/sylius` tomorrow, should be fixed then.

**Comment by nietzcheson** [comment]
I'm waiting the updated ✌️

**Comment by michalmarcinkowski** [comment]
@Zales0123 is working on that (see https://github.com/Sylius/Sylius-Standard/pull/130).

**Comment by nietzcheson** [comment]
I saw, thanks!

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
