### ISSUE TITLE
#Command: sylius:install --env=prod failed

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius-Standard#132]
I'm trying to install a standard edition Sylius with the command **php app/console sylius:install --env = prod**

This throws me the following error:

[Symfony \ Component \ Debug \ Exception \ FatalErrorException]

Compile Error: Can not declare class Gedmo \ Loggable \ Entity \ MappedSuperclass \ AbstractLogEntry, Because the name is already in use

**Comment by lchrusciel** [comment]
It works with current master

![zrzut ekranu 2016-10-20 o 09 03 40](https://cloud.githubusercontent.com/assets/6213903/19549354/21f6dff8-96a4-11e6-9bb8-60026e7c3da4.png)

Can be closed /cc @michalmarcinkowski @pjedrzejewski
