### ISSUE TITLE
Stock sufficiency not checked correctly on adding item to cart

### ISSUE THREAD

**Issue by blankcheck** [Sylius/Sylius-Standard#135]
When adding product to cart, stock sufficiency is checked only against quantity entered in quantity field. For example:

 - we have product A with inventory on hand of 5
 - adding more than 5 instances of product A to cart will trigger error
 - adding subsequently <=5 instances of A will not trigger error, meaning you can have as many as you want of A in your cart regardless of stock level

Bottom line is, on adding items to cart, stock should be checked against quantityBeingAdded + quantityExistingInCart for particular product.
 
Granted, you will not be able to finish order because of last check before order completion, but still.

As a quick and dirty fix I used availability checker within OrderItemController in combination with orderItemResolver:

```

$cart = $this->getCurrentCart();
$availabilityChecker = $this->get('sylius.availability_checker.default');
if(!$availabilityChecker->isStockSufficient($newResource->getVariant(), $this->resolveTotalItemQuantity($cart, $newResource))) {
	// do something
};

private function resolveTotalItemQuantity(OrderInterface $order, OrderItemInterface $item)
{
	foreach ($order->getItems() as $existingItem) {
		if ($item->equals($existingItem)) {
			return $existingItem->getQuantity() + $item->getQuantity();
		}
	}

	return $item->getQuantity();
}

```

**Comment by michalmarcinkowski** [comment]
Fixed in #6712.
