### ISSUE TITLE
[behat] - Run bin/behat

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius-Standard#144]
I want to run behat with the console command: bin/behat and throw me:

[Behat \ Testwork \ ServiceContainer \ Exception \ ExtensionInitializationException]
   `FriendsOfBehat \ SymfonyExtension` extension file or class could not be located.

Any ideas?

**Comment by nietzcheson** [comment]
And installed the bundle *composer require friends-of-behat/symfony-extension --dev* and added in the *FriendsOfBehat\SymfonyExtension: ~* behat.yml. The failure continues

**Comment by michalmarcinkowski** [comment]
Works on master.
