### ISSUE TITLE
Warning executing composer install after switch to beta

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius-Standard#146]
Hi there. After switching to sylius beta, whenever i do a `composer install` i get two warnings:
```
Warning: Ambiguous class resolution, "AppKernel" was found in both "$baseDir . '/app/AppKernel.php" and "/.../project/vendor/sylius/sylius/app/AppKernel.php", the first will be used.
Warning: Ambiguous class resolution, "AppCache" was found in both "$baseDir . '/app/AppCache.php" and "/.../project/vendor/sylius/sylius/app/AppCache.php", the first will be used.
```

Is this intended for some reason? Shod we probably remove the ones from they sylius/sylius?

Thank you!

**Comment by pjedrzejewski** [comment]
We should definitely get rid of that warning, although it is harmless to your app, only confusing for the dev. Not sure there is an easy way.

**Comment by alcaeus** [comment]
@pjedrzejewski I gave this a look - having AppKernel and AppCache in the classMap in sylius/sylius and sylius/sylius-standard is the cause for this. I'm not sure there's any other fix than reverting that change and requiring `AppKernel.php` manually in `web/app.php`, as was done before Beta-1.

**Comment by pjedrzejewski** [comment]
@alcaeus I think you are right, @pamil was there any good reason to do this when upgrading to Symfony 3.2? I think it does not do any harm, while this message is quite confusing.

**Comment by pamil** [comment]
@alcaeus @pjedrzejewski I've just followed the Symfony-Standard repo both on Sylius and Sylius-Standard. Anyway, I think that `Sylius/Sylius` should be never installed without dev dependencies, so we may want to add these files to `autoload-dev`, so they won't be included on Sylius-Standard.
