### ISSUE TITLE
composer install problem

### ISSUE THREAD

**Issue by djacquel** [Sylius/Sylius-Standard#15]
As described in [the quick install doc](http://sylius.org/get-started) and
 trying

    # with composer globally installed
    composer create-project sylius/sylius-standard
    #or
    # with a local phar archive
    php composer.phar create-project sylius/sylius-standard

I get a **Could not find package sylius/sylius-standard with stability stable**

Doing a **composer init** and then copying the current master composer.json works.

The quick start guide is not in sync as no **stable** version is available.

**Comment by cjuhong** [comment]
@timon-schroeter  

not work for me, I get a Could not find package sylius/sylius-standard, my vendor/sylius folder is empty.

**Comment by michalmarcinkowski** [comment]
Not an issue anymore.
