### ISSUE TITLE
Doctrine annotations error when editing a product from sample db

### ISSUE THREAD

**Issue by denis-rendler-evozon** [Sylius/Sylius-Standard#150]
Hello! Every time I want to edit a product, on save I get this error.
[Semantical Error] The annotation "@Doctrine\ORM\Mapping\Column" in property Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry::$id does not exist, or could not be auto-loaded.

Any ideas?

**Comment by pjedrzejewski** [comment]
What is your Sylius version? :)

**Comment by denis-rendler-evozon** [comment]
hi @pjedrzejewski. 

the version is 1.0.0-alpha.1

**Comment by denis-rendler-evozon** [comment]
this issue is fixed in beta-1. thanks
