### ISSUE TITLE
Locale and database_driver should be remove from parameter files

### ISSUE THREAD

**Issue by Soullivaneuh** [Sylius/Sylius-Standard#154]
Those variable do not have any reason to be modified dynamically on production servers.

It's part of the application definition.

See also: https://github.com/symfony/symfony-standard/commit/f0f95828a7fa2cabf784a367584394475f6a73f6

**Comment by pjedrzejewski** [comment]
Agree for the ``locale``, but not sure about the driver? Thanks for the suggestion!

**Comment by pamil** [comment]
Removing database driver parameter looks good to me, no reason to make it so easily configurable.
