### ISSUE TITLE
In sylius_channel_pricing table variant/channel combination not unique

### ISSUE THREAD

**Issue by blankcheck** [Sylius/Sylius-Standard#158]
Not sure if this is a bug or it is like that by design, but I would think that product_variant_id/channel_id combination of columns should be unique in sylius_channel_pricing table.

Without this constraint on db, we can have multiple prices for same variant on same channel.

This would make sense if there are plans to introduce something like "price_type" (i.e. onlinePrice, discountPrice...) but then again uniqueness should be forced on variant/channel/priceType.

**Comment by lchrusciel** [comment]
It is a missing feature, I guess. Different price can be handled on a same entity probably. Are you willing to open a PR with fix? If so, please open it to [main Sylius repo])(https://github.com/Sylius/Sylius)

**Comment by blankcheck** [comment]
I am, but we first need to agree on what do we actually want to do here out of these options:

1. just make sure that product_variant_id/channel_id are unique
2. introduce this so called priceType option

Regarding 2, we again have few options:

2.1
priceType (at least in most ecommerce systems I dealt with) usually boils down to "normal price" and "sale price". For this we could likely use sylius_channel_pricing with just additional column were we would have constants i.e. 'default' or 'sale'
2.2
Second solution would be to make priceType totally defined by users (they could CRUD price types) and then we have FK in sylius_channel_pricing

Out of all these, I would suggest 2.1 (because I see it as needed functionality), while 2.2 seams to me like an overkill without real added value to it in most cases.

Let me know.

**Comment by lchrusciel** [comment]
Probably we will go with at the end with 2.1 but we will have price and original price. Anyway, we can introduce a unique constraint to product_variant_id/channel_id and then in another PR add feature with original price. 

/cc @michalmarcinkowski

**Comment by pjedrzejewski** [comment]
It is a bug. There should be a constraint.

**Comment by blankcheck** [comment]
We have same problem on sylius_product_taxon - no constraint on product_id/taxon_id combination.

I checked other entities where we have "many-to-many with additional columns" and others seam fine in regard to constraints.

**Comment by pjedrzejewski** [comment]
@blankcheck Could you open a PR with fixes to both entities, please? :)

**Comment by blankcheck** [comment]
Will do, np.
