### ISSUE TITLE
autoload psr-4 in composer.json 

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius-Standard#163]
Hello,

I'm using `Sylius/Sylius-Standard`,

I'm new to symfony & composer, so I spent a lot of time figuring out why my custom bundles wasn't autoloaded, this reason is because in the [composer.json](https://github.com/Sylius/Sylius-Standard/blob/master/composer.json) of `Sylius/Sylius-Standard`, the autoload section is : 
```javascript
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle/"
        },
        "classmap": ["app/AppKernel.php", "app/AppCache.php"]
    },
```
I think it should have a `"": "src/"` like this : 
```javascript
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle/",
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php", "app/AppCache.php"
        ]
    },
```

or even : 
```javascript
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php", "app/AppCache.php"
        ]
    },
```

**Comment by brunocombodo** [comment]
on the original issue, @pamil said : 

> It will affect the Composer autoloader performance (without dumped classmap) - looking for class `Symfony\Foo` it would check `src/Symfony/Foo.php` first and then `vendor/symfony/symfony/src/Symfony/Foo.php`.
> 
> However it is the way Symfony-Standard handles it, so we might want to do the same in order to be more similar to them.

**Comment by adamelso** [comment]
It's a balancing act between usuability and optimization. Personally any developer worth their salt would use `--optimize-autoloader` or a custom autoload configuration in Composer, but for those getting started, just give them `"psr-4": { "": "src" },` [as Symfony do](https://github.com/symfony/symfony-standard/blob/master/composer.json#L7).

**Comment by wl520a** [comment]
"AppBundle\\": "src/AppBundle"
          ,"Acme\\LarryBundle\\": "src/Acme/LarryBundle" //this is my new bundle

I also meet this issue, but I update my composer.jsaon, it works.

**Comment by Ferror** [comment]
The issue is from 2017 and the current composer.json file was updated to the best possible state:
```
"autoload": {
    "psr-4": {
        "App\\": "src/"
    }
},
```
