### ISSUE TITLE
Build is broken without the cache

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius-Standard#173]
I just pushed recent changes to my fork and realised that the build is broken on javascript scenarios. 

[Referenced build](https://travis-ci.org/lchrusciel/Sylius-Standard/builds/257215831?utm_source=github_status&utm_medium=notification).

**Comment by pamil** [comment]
👍 , but let's wait for Sylius/Sylius#8293 with it.

**Comment by pamil** [comment]
Working correctly now.
