### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by MikhailS01** [Sylius/Sylius-Standard#178]
If I try to create new project on OpenServer(Win): 
composer create-project -s beta sylius/sylius-standard acme
cd acme
And then the command:
**php bin/console sylius:install**
it fails on the second step with error:

> Step 2 of 4. Setting up the database.
> -------------------------------------
> 
> Creating Sylius database for environment dev.
>  2/3 [тЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦСтЦС         ]  66%
> 
>   [Symfony\Component\Config\Exception\FileLoaderLoadException]
>   Warning: glob(): Pattern exceeds the maximum allowed length of 260 characters in D:\OpenServer\OpenServer\domains\sylius-test.dom\vendor\sylius\sylius\src\Sylius\Bundle\AdminBundle/Resources/config/routi
>   ng/admin_user.yml (which is being imported from "D:\OpenServer\OpenServer\domains\sylius-test.dom\vendor\sylius\sylius\src\Sylius\Bundle\AdminBundle/Resources/config/routing.yml").
> 
> 
> 
>   [Symfony\Component\Debug\Exception\ContextErrorException]
>   Warning: glob(): Pattern exceeds the maximum allowed length of 260 characters
>

**Comment by Zales0123** [comment]
I believe it can be closed, lots of time has passed since this issue, lots of new Sylius releases as well :)
