### ISSUE TITLE
DAMADoctrineTestBundle was unintentionally removed

### ISSUE THREAD

**Issue by JanTvrdik** [Sylius/Sylius-Standard#200]
Commit e8a558f4681197cf5d4f5ee6e15c7f8a8a19d371 unintentionally removed DAMADoctrineTestBundle.

https://github.com/Sylius/Sylius-Standard/commit/e8a558f4681197cf5d4f5ee6e15c7f8a8a19d371#commitcomment-24433482

**Comment by pamil** [comment]
Actually I've removed it from Sylius in https://github.com/Sylius/Sylius/pull/8117 as it made debugging database issues impossible. I've spent quite some time figuring out why changes aren't persisted correctly before I came to the conclusion. I'm not sure if it's worth it, it's a developer experience / tests time trade-off.
