### ISSUE TITLE
AppKerne_::getCacheDir() is not compatible

### ISSUE THREAD

**Issue by JanSuchanek** [Sylius/Sylius-Standard#203]
$ composer create-project sylius/sylius-standard acme
$ cd acme
$ php bin/console sylius:install

Fatal error:  Declaration of AppKerne_::getCacheDir() must be compatible with Sylius\Bundle\CoreBundle\Application\Kernel::getCacheDir(): string in /sylius/acme/var/cache/de_/kernel.tmp on line 49

Fatal error: Declaration of AppKerne_::getCacheDir() must be compatible with Sylius\Bundle\CoreBundle\Application\Kernel::getCacheDir(): string in /sylius/acme/var/cache/de_/kernel.tmp on line 49
                                                                                                                                                     
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                            
  Compile Error: Declaration of AppKerne_::getCacheDir() must be compatible with Sylius\Bundle\CoreBundle\Application\Kernel::getCacheDir(): string

**Comment by JanSuchanek** [comment]
Problem only in PHP 7.2, switch to PHP 7.1  [Sylius bugs list](https://github.com/Sylius/Sylius/issues/8757)

**Comment by danielsteiner** [comment]
Nope. It's not just in PHP 7.2 - I get this error with 7.1.2RC2 as well.

**Comment by JanSuchanek** [comment]
Ok, i install php7.1 in homebrew and working fine.
