### ISSUE TITLE
Platform's PHP version

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius-Standard#235]
https://github.com/Sylius/Sylius-Standard/pull/230#discussion_r194696609

**Comment by jacquesbh** [comment]
Can we close?

**Comment by alexander-schranz** [comment]
I think setting the platform version is not a good idea as 7.2 will be interpreted as 7.2.0 and this behaviour will not be changed by composer see https://github.com/composer/composer/issues/8144.
So if a requirement requires a newer version e.g. 7.2.1 or 7.3 it will not be installed or an old version get installed. Maybe its possible to provide a composer `post-root-package-install` script which does replace the php platform verison with the current used php version which can be provided by [phpversion()](https://www.php.net/manual/de/function.phpversion.php)

**Comment by pamil** [comment]
@alexander-schranz it sounds like a great idea!
