### ISSUE TITLE
Composer TransportException - adrianmacneil/omnipay/zipball - file could not be downloaded

### ISSUE THREAD

**Issue by pdrosos** [Sylius/Sylius-Standard#24]
Hi guys,

When I am trying to install Sylius/Sylius-Standard via Composer, I receive this error, which interrupts the installation process:

 [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/adrianmacneil/omnipay/zipball/4f5e82232161939c0b14f5921c092ed77980d450" file could not be downloaded (HTTP/1.1
  404 Not Found)

Could someone help me with this issue?

Thanks a lot!

**Comment by michalmarcinkowski** [comment]
Shouldn't be a case anymore.
