### ISSUE TITLE
Run tests inside Docker

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius-Standard#245]
Our Docker setup should be able to run the same tests as is run by vanilla PHP suite.

**Comment by jacquesbh** [comment]
@pamil I think this is working, right?

**Comment by teohhanhui** [comment]
No. Currently tests are not run from inside the Docker container on Travis CI.

**Comment by jacquesbh** [comment]
What are the docker suite about then? Is it just the compilation of the images?

**Comment by teohhanhui** [comment]
Yes. Basic smoke testing to make sure that the Docker image / container works.

**Comment by Ferror** [comment]
Running tests inside the docker container is possible, but it will take a lot of additional time. Therefore I don't think there is a value in here.
