### ISSUE TITLE
Document Docker usage

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius-Standard#246]
- How to use Docker provided with this repository for development / staging / test / production?
- Running tests inside Docker
- Developing inside Docker (XDebug setup?)

**Comment by quintanilhar** [comment]
I can do this. I'm actually suffering to configure Docker after the 1.3 release, would be great to document everything to help others in the future. :)

**Comment by teohhanhui** [comment]
@quintanilhar What were the problems you've run into? It'd be great if you could share them so that I could take a look. :)

**Comment by quintanilhar** [comment]
hey @teohhanhui, when I ran ```docker-compose up -d``` for a fresh application, I got this error:

![image](https://user-images.githubusercontent.com/1084316/47183823-551ec580-d329-11e8-9d3f-c84a71a9926f.png)

After I added the required env variable in the Dockerfile, I got a different error:

![image](https://user-images.githubusercontent.com/1084316/47185076-bf853500-d32c-11e8-9b6d-9237cb603dc0.png)

So I changed the APP_ENV from prod to dev in the Dockerfile and then I had one more issue with the memory limit when clearing the cache.

**Comment by teohhanhui** [comment]
The problems you're having seem unusual. But anyway, please do not change the `Dockerfile` like that. The environment variables are passed in from `docker-compose.yml`

**Comment by Ferror** [comment]
Done some time ago
