### ISSUE TITLE
Use Symfony flex and Symfony 4 folder structure

### ISSUE THREAD

**Issue by pierre-H** [Sylius/Sylius-Standard#250]
Hello !

First, thanks for Sylius : it's a great Framework !

When will you update Sylius to Symfony flex and Symfony 4 folder structure ?
The new system is so easy :)

Thanks !

**Comment by pamil** [comment]
Great timing, I started to work on that this morning, see Sylius/Sylius#9643! :)

**Comment by diimpp** [comment]
Hi,

are there any plans for this before 1.3, which is I assume planned for late September? 

I'm starting a new symfony4/sylius project and wondering if I should tackle it myself locally or start with current version and port to flex dir style later on.

**Comment by diimpp** [comment]
Ok, I guess it's not possible to use flex directory structure until Sylius will remove `symfony/symfony` dependency.

**Comment by teohhanhui** [comment]
@diimpp Did you see the linked PR? https://github.com/Sylius/Sylius/pull/9643

**Comment by diimpp** [comment]
@teohhanhui I've did, but Sylius#master still uses `symfony/symfony` https://github.com/Sylius/Sylius/blob/master/composer.json#L60 dependency, which makes it impossible (To my knowledge) to use flex.

I've tried to install Sylius 1.2 and 1.3@dev on `Symfony4-skeleton` without success.

**Comment by teohhanhui** [comment]
Uhh, yes, guess we have to wait for the next PR from @pamil 🥇

**Comment by pamil** [comment]
@diimpp yeah, `symfony/symfony` is getting removed from `sylius/sylius` requirements in a next PR which introduces Flex :)

**Comment by Bonobomagno** [comment]
so you did it on 1.2.6?
Do you think to add documentation of suggested way to manage new projects?

**Comment by pamil** [comment]
The changes will be included in `1.3.0` release, which is scheduled for the very end of September, so there's a plenty of time for polishing and documenting the new flow.

**Comment by Bonobomagno** [comment]
Thanks. this was not clear becouse you are talking about supporting symfony 4 from 1.2. 
You closed the symfony 4 support issue on sylius-standard, making think that the work is done.

I think that will be better to explain that on the readme, something like (still on symfony3)

**Comment by teohhanhui** [comment]
@Bonobomagno Sylius 1.2 supports Symfony 4.1, but it does not use Symfony Flex and is on the old directory structure.

**Comment by pamil** [comment]
Sylius-Standard is on new directory structure and supporting Symfony Flex now.
