### ISSUE TITLE
es6, new default way to customize js/css with rollup? not a bc?

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius-Standard#255]
new gulp version, rollup and babel added and all the codin es6.
I like that, but we will need a migration path. 
Not only, now that es6 is out of the box, we need a way to make use of it, inside our AppBundle.

In fact with gulp 4 this is easy, we can add a gulp.series that chain after the parallel (admin, shop) our custom pipeline.
The bad thing is that still there are no default pipeline for AppBundle case (and for who is new to rollup till last month, this is a BC) .

so any plan about this?

**Comment by Bonobomagno** [comment]
suggested way to handle the AppBundle.
Make a new gulpfile.
css/sass/img tasks can be rewrited just adding  your own directory on the paths.

Add a admin - shop directory on AppBundle/Resources/private/admin-or-shop/js-css-etc
So now you need only 1 gulfile for both admin and shop.

For the javascript, you will generate 2 bundle files /vendor and app.js
Copy the original bundler on your custom gulpfile and make it create a vendor.js instead of app.js

now use rollup for your custom app.js (without plugin or shim, because sylius expose and extend $, so no need for nothing )

On last step you need to edit the layout.html.twig (for admin and shop) adding vendor.js before app.js
(css and image dont need that, ofc)

tip: add "del" for clean the assets dir before every compile.

**Comment by teohhanhui** [comment]
Hi, I have plans to contribute an app `gulpfile`. But actually it's better if we can have only one `gulpfile`. It removes a lot of problems and allows us to do tree-shaking properly.

But of course you're right, we need to think of the migration path. Though I think it's a necessary pain.

WDYT @pamil?

**Comment by Bonobomagno** [comment]
so you plan to remove the 2 bundle gulpfile?
I still think that just splitting custom and default assets it is a good start.
If you plan to change, why not webpack encore? this is the new default in symfony house

**Comment by Ferror** [comment]
Gladly we have it moved to webpack 😄
