### ISSUE TITLE
Docker 502 Bad Gateway

### ISSUE THREAD

**Issue by doctorx32** [Sylius/Sylius-Standard#267]
Hi, after complete project deploying with Docker browser was received "502 Bad Gateway", and in nginx logs are this error:

> *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /en_US HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "sy-current.local"

It looks like after https://github.com/Sylius/Sylius-Standard/pull/258 there are not available web/app{_dev}.php files.

**Comment by pamil** [comment]
#271 should solve this one, please open another issue if that's not a case.

**Comment by NicolasGraph** [comment]
In my case, following the instruction at line 13 of `docker/nginx/conf.d/default.conf` fixed the issue: I had to comment `fastcgi_pass $backendfpm;` and uncomment `resolver 127.0.0.11;`.
