### ISSUE TITLE
symfony-cmd not found during deployment when deploying using composer's --no-dev

### ISSUE THREAD

**Issue by markahesketh** [Sylius/Sylius-Standard#287]
When I do a `composer install --no-dev` during a deployment to Dokku, I am running into the following error when `@auto-scripts` runs as symfony/flex is not installed:

```
remote:        > symfony-cmd
remote:        sh: 1: symfony-cmd: not found
remote:        Script symfony-cmd handling the auto-scripts event returned with error code 127
remote:        Script @auto-scripts was called via post-install-cmd
```

This occurs for a new project created using `composer create-project sylius/sylius-standard acme`.

`symfony/flex` is currently a `require-dev` dependency, from this PR (https://github.com/Sylius/Sylius/pull/9716), and so is not installed due to the `--no-dev` flag.

Assuming there are no plans to making `symfony/flex` a `require` dependency, I suppose the way these scripts are run needs updating?

**Comment by Prometee** [comment]
There is also other problems after resolving this, see #288

**Comment by pamil** [comment]
I've opened a PR that moves Flex to require (#289).

**Comment by pamil** [comment]
#289 merged 🎉

**Comment by markahesketh** [comment]
Thanks @pamil !
