### ISSUE TITLE
There are no commands defined in the "doctrine:phpcr:repository" namespace

### ISSUE THREAD

**Issue by patkar** [Sylius/Sylius-Standard#29]
A few days ago `sylius:install` worked, but today with a fresh install via composer I get the following error

    Creating database schema...
    Database schema created successfully!

    [InvalidArgumentException]                                                   
    There are no commands defined in the "doctrine:phpcr:repository" namespace.

I think this is a result from removing the composer.lock as the sylius bundles were locked to a state aprox. 3 months ago where symfony-cmf wasn't introduced.

Possible solutions:
* add the symfony-cmf bundles as require to this SE, or
* add the symfony-cmf to the corresponding sylius bundles, which needs them (SyliusInstallerBundle, which else?), or
* both?

I know in sylius/sylius this dependency is defined, but that's not helpfull in the SE as it requires the core-bundle not sylius itself.

P.S.: To not forget about acitvating the bundles in the kernel and the config ^^ And the AnnotationRegistry in autoload.php

@pjedrzejewski what do you suggest?

**Comment by michalmarcinkowski** [comment]
It has been fixed.
