### ISSUE TITLE
Database connection fails

### ISSUE THREAD

**Issue by aario-sitewards** [Sylius/Sylius-Standard#292]
`bin/console sylius:install ` fails connecting database on version 1.3.0.
This is what I found in the cached php file:
```
var/cache/dev/ContainerIM1r40l/srcDevDebugProjectContainer.php
```
Which sets password as `NULL`:
```
return $this->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array()))->createConnection(array('driver' => 'pdo_mysql', 'charset' => 'UTF8', 'url' => $this->getEnv('resolve:DATABASE_URL'), 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => array(), 'serverVersion' => '5.7', 'defaultTableOptions' => array()), $a, $d, array());
```
In a working version 1.1 cloned within Sylius/Docker docker file the same line contains:
```
:        return $this->services['doctrine.dbal.default_connection'] = ${($_ = isset($this->services['doctrine.dbal.connection_factory']) ? $this->services['doctrine.dbal.connection_factory'] : $this->services['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array())) && false ?: '_'}->createConnection(array('driver' => $this->getEnv('SYLIUS_DATABASE_DRIVER'), 'host' =>
$this->getEnv('SYLIUS_DATABASE_HOST'), 'port' => $this->getEnv('SYLIUS_DATABASE_PORT'), 'dbname' => $this->getEnv('string:SYLIUS_DATABASE_NAME').'_dev', 'user' => $this->getEnv('SYLIUS_DATABASE_USER'), 'password' => $this->getEnv('SYLIUS_DATABASE_PASSWORD'), 'charset' => 'UTF8', 'driverOptions' => array(), 'serverVersion' => '5.5', 'defaultTableOptions' => array()), $c, $i, array());
```
So the old version is much longer and contains getEnv commands to get these parameters from the environment. So currently using version 1.3 is impossible unless we know what environment parameters to set or fix this bug.
Thanks in advance.

**Comment by aario-sitewards** [comment]
Update: Issue repeated on v1.3.1.
```
Creating Sylius database for environment dev.

In AbstractMySQLDriver.php line 113:

  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 50:

  SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 46:

  SQLSTATE[HY000] [2002] Connection refused

```

**Comment by aario-sitewards** [comment]
Update: Issue repeated on v1.3.2.
{code}
Step 2 of 4. Setting up the database.
-------------------------------------

Creating Sylius database for environment dev.

In AbstractMySQLDriver.php line 113:
                                                                              
  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                              

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

sylius:install:database [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
{code}

**Comment by pamil** [comment]
Sorry for the late reply, have you set `DATABASE_URL` env variable in either dotenv files or in your environment? All the default settings are overridden by contents of that variable.

**Comment by andreshgz** [comment]
aha! @pamil thanks for your reply... and how do we set the proper DATABASE_URL in the environment? #newbie
