### ISSUE TITLE
Just nothing works...

### ISSUE THREAD

**Issue by jujusous3** [Sylius/Sylius-Standard#3]
Hi !

I want to build a new project using Sylius.
It seems really awesome, but it's been an entire week I'm facing to installation errors, bugs in the application...etc

If I understand, for a new project, I have to use sylius/sylius-standard.
So I do : 

composer create-project -s dev sylius/sylius-standard
(on the http://sylius.org/get-started, the "-s dev" is not present, but without it it doesn't work).

Next, I do : 

cd sylius/sylius-standard
php app/console sylius:install

Everything begins good, but at the end I have an error : 

[InvalidArgumentException]                                                   
  The "/Users/Juju/Sites/sylius-standard/app/../web/fixtures" directory does   
  not exist. 

So, I create this folder manually, next I do : 

php app/console doctrine:fixtures:load

But now I have this error : 

[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Notice: Undefined index: Sylius.Image.sticker in /Users/Juju/Sites/sylius-s  
  tandard/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Refe  
  renceRepository.php line 145    

So, even if I have this error, I try to go to the website.
It seems work, I place an order, but when I finalize the order (checkout/finalize/forward), I have this error : 

A new entity was found through the relationship 'Sylius\Bundle\CoreBundle\Model\Order#user' that was not configured to cascade persist operations for entity: sylius@example.com. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

So, is there anyway to make Sylius works ?
Before that, I used Sylius/sylius, all works good, but there was a big bug (no number generated for orders) so customers can't simply see there orders...

Any help ? I'm desperate ...

Thanks a lot ;)

**Comment by michalmarcinkowski** [comment]
Not an issue anymore.
