### ISSUE TITLE
Why is src copied in Dockerfile and not mounted as volume in docker-compose.yml?

### ISSUE THREAD

**Issue by gvlasov** [Sylius/Sylius-Standard#325]
I'n on ~1.3.0

As I understand, you store your code in `src`. When I work on my website locally with it running in Docker, I want to make changes to my code in `src` and see the results right away. But copying src into the image at build time doesn't allow for that, I'd have to rebuild the container to see the changes. Am I getting something wrong here?

**Comment by kboduch** [comment]
@gvlasov This is related to a practice where you deploy docker containers based on the images with "build in code". The code is read-only (except cache, media etc. folders).

**Comment by gabiudrescu** [comment]
@gvlasov if you use the docker-compose you will have the src also mounted as a volume, in development mode;
