### ISSUE TITLE
An exception occurred while executing 'SELECT DISTINCT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, s0_.id AS id_4, 

### ISSUE THREAD

**Issue by christiankasse** [Sylius/Sylius-Standard#328]
I have an error when I access the navigation bar and I can not understand the source of the error while I made the migration and I did not touch the reques

`An exception occurred while executing 'SELECT DISTINCT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, s0_.id AS id_4, s0_.variant_selection_method AS variant_selection_method_5, s0_.average_rating AS average_rating_6, s1_.name AS name_7, s1_.slug AS slug_8, s1_.description AS description_9, s1_.meta_keywords AS meta_keywords_10, s1_.meta_description AS meta_description_11, s1_.id AS id_12, s1_.short_description AS short_description_13, s1_.locale AS locale_14, s0_.main_taxon_id AS main_taxon_id_15, s1_.translatable_id AS translatable_id_16 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?) INNER JOIN sylius_product_taxon s2_ ON s0_.id = s2_.product_id INNER JOIN sylius_taxon s3_ ON s2_.taxon_id = s3_.id WHERE s3_.tree_left >= ? AND s3_.tree_right <= ? AND s3_.tree_root = ? AND EXISTS (SELECT 1 FROM sylius_product_channels s4_ INNER JOIN sylius_channel s5_ ON s4_.channel_id = s5_.id WHERE s4_.product_id = s0_.id AND s5_.id IN (?)) AND s0_.enabled = 1 ORDER BY s2_.position ASC LIMIT 9' with params ["en_US", 2, 3, 1, 2]:`
`SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'agromwinda_dev.s2_.position' which is not in SELECT list; this is incompatible with DISTINCT`

Please Help

**Comment by Zales0123** [comment]
It should be resolved by https://github.com/Sylius/Sylius-Standard/issues/328, thank you for reporting this!

**Comment by skillberto** [comment]
> It should be resolved by #328, thank you for reporting this!

Dear @Zales0123,

I have similar problem.
This is the #328, then which issue resolve this problem?

Thank you!

**Comment by skillberto** [comment]
> > It should be resolved by #328, thank you for reporting this!
> 
> Dear @Zales0123,
> 
> I have similar problem.
> This is the #328, then which issue resolve this problem?
> 
> Thank you!

My question is not relevant already, I could fix it with `composer update` from `sylius 1.6.4` to `1.6.5` what downgraded the `grid bundle` to `1.7.3` from` 1.7.4.`
