### ISSUE TITLE
Extended model should be @Entity intead of @MappedSuperclass

### ISSUE THREAD

**Issue by pcabreus** [Sylius/Sylius-Standard#332]
The Sylius-Standard already comes with  extended entities for each model of Sylius main package. This avoid you to create entities by yourself and configure it.
The problem is when I try to add more field to this entities (``@ORM\Column(type="datetime")`` to `$publishStartDate` in `App\Entity\Product\Product` for example). When I try to update my schema it seems like nothing was done in the entity.
I could solved my problem by changing the annotation @MappedSuperclass for @Entity (It's my code in `src` so it's not a problem). But why this entities are mapped as superclasses.
It is a good idea @MappedSuperclass to Sylius bundles but I think in Standard it not makes sense because those entities wont be extended, they will be Entities always.

PD: Sorry if I made a mistake on my English

**Comment by Prometee** [comment]
I also agree with @pcabreus Doctrine also warn us when we list the mapping infos : `php ./bin/console doctrine:mapping:info`
Many people on Slack are asking why there are not `@Entity` instead of `@MappedSuperclass`

ping @pamil @Zales0123 ?

**Comment by pamil** [comment]
Sorry for the late reply, it is definitely a bug in the provided models mapping. Could you provide a PR which changes it (targeting `1.4` branch)?

**Comment by pamil** [comment]
Anyway, it seems like `AddressLogEntry` with `@Entity` annotation breaks, because there's annotation mapping in the inherited model and YAML mapping which duplicates the former one, but it should not prevent us from changing it from `MappedSuperclass` to `Entity`.

**Comment by pcabreus** [comment]
I saw the problem with `AddressLogEntry` and I spent a lot of time trying to solve it but I couldn't. I end up making a dummy example of mappedSuperclass of 3 level of inheric with overrides and I find out it doesn't work 😣. Which is the case of `AddressLogEntry` it has its own mapping but extends of `Gedmo...AbstractLogEntry` which also have a mapping via @annotation. If you extends from the address as an entity you have an error for duplicate fields, if you remove AddressLogEntry mapping (PR) you change some custom difference on the mapping and if you overrides like doctrine says you get a error of invalid fields (I tried with dummies classes `A` MSuperclass, `B` MSuperclass with an override for a field of `A` and `C` Entity extends of `B` and override doesn't work)
I dont really know what to do. "Nobody" extends AddressLogEntry and that is (maybe) why it is not a big issue. But it is.
So I should make a PR with @Entity or why for a solution for Sylius/Sylius on that mapping???

**Comment by pcabreus** [comment]
I've found a problem with MappedSuperclass on Doctrine which is easy to reproduce https://github.com/doctrine/orm/issues/7678  It prevent us to extend from `AddressLogEntry` MappedSuperclass, because this one extends from `AbstractLogEntry` MappedSuperclass, and it's like you have both mapping at the same time, no by inheric.
For other hand, AnnotationDriver have some problem with MappedSuperclass and its `protected` fields.
