### ISSUE TITLE
[Docker on Mac] Error while loading features 

### ISSUE THREAD

**Issue by vichanse** [Sylius/Sylius-Standard#341]
I'm having this issue when i try to load features

```
docker-compose exec php bin/console sylius:fixtures:load --no-interaction

Warning: require(/srv/sylius/vendor/autoload.php): failed to open stream: No such file or directory in /srv/sylius/bin/console on line 11

Fatal error: require(): Failed opening required '/srv/sylius/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /srv/sylius/bin/console on line 11
```

Any clue on how i can solve this?

**Comment by noreff** [comment]
Have the same issue, MacBookPro 11,4, macOS 10.13.6 (17G5019)

**Comment by anthonymartin** [comment]
Can you try running `docker-compose exec composer install` before running `docker-compose exec php bin/console sylius:fixtures:load --no-interaction` and see if that works?

**Comment by TofaVoe** [comment]
Same problem here :( `docker-compose exec composer install`  ends with `ERROR: No such service: composer`. I had this problem with Sylius before by my own, so I followed this tutorial and still dont work: https://jokiruiz.com/sylius/how-to-set-up-docker-for-sylius-projects/

**Comment by julienmession** [comment]
Old question, but same issue today.
With docker-compose, you need to indicate the service on which you want to exec some command.
Try `docker-compose exec **php** composer install`
Worked for me.

**Comment by tweinreich** [comment]
@julienmession thank you this helped me to get one step further. At least instead of a 502 I now get some errors:

**Shell:**
```shell
 docker-compose exec php bin/console sylius:fixtures:load --no-interaction

In AbstractMySQLDriver.php line 46:

  An exception occurred while executing 'DELETE FROM sylius_channel_currencies':

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_channel_currencies' doesn't exist


In PDOConnection.php line 46:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_channel_currencies' doesn't exist


In PDOConnection.php line 41:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sylius.sylius_channel_currencies' doesn't exist


sylius:fixtures:load [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<suite>]
```

And when I visit `localhost` with my browser I get the following error:

```
An exception has been thrown during the rendering of a template ("Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.") in "@SyliusShop/Layout/Topbar/_currencySwitcher.html.twig".
```

I do not expect you to fix this. I just want to document it in case anyone else runs into this issue.
