### ISSUE TITLE
Override SyliusWebBundle:Frontend:layout.html.twig in sylius-standard

### ISSUE THREAD

**Issue by maiksuaco** [Sylius/Sylius-Standard#35]
I am using sylius-standard as vendor and I want to override my layout but when I put in my  layout in my app/Resources/SyliusWebBundle/Frontend/layout.html.twig I and after clear:cache It continue reading template from WebBunde in vendor directory...I need help with that...Theres a strange behavior there...

**Comment by michalmarcinkowski** [comment]
Standard Symfony way of overriding templates works fine, please follow [the docs](http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates).
