### ISSUE TITLE
Why does the docker setup runs composer install twice?

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius-Standard#351]
Once is ran here: https://github.com/Sylius/Sylius-Standard/blob/master/Dockerfile#L82

and another time is ran here: https://github.com/Sylius/Sylius-Standard/blob/master/docker/php/docker-entrypoint.sh

ok, the 2nd time is ran only if the env is DEV, but stilll, why? cc @teohhanhui

**Comment by teohhanhui** [comment]
@gabiudrescu Because otherwise we cannot ensure that the `vendor` is correct, due to the use of volumes.

**Comment by teohhanhui** [comment]
Also, because the `composer install` in the `Dockerfile` is for `prod` environment.

**Comment by gabiudrescu** [comment]
I see. it makes sense. but can this be avoided in any way?

**Comment by teohhanhui** [comment]
I don't see any way it could be avoided, or why it should be avoided. If this happens in the `prod` env, it's bad, but it's not. :smile:

**Comment by gabiudrescu** [comment]
fair enough. thanks for the clarification, @teohhanhui

**Comment by lchrusciel** [comment]
@teohhanhui shouldn't we add `--no-dev` to Dockerfile then?
