### ISSUE TITLE
Building docker-compose environment, what are the Credentials for the admin-user?

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius-Standard#365]
I have build the `docker-compose`-environment. The main page can't be loaded as an exception "Channel could not be found!" was raised.

Therefor I tried to signin into admin-dashboard and to create channels.

However, what are the default credentials for admin-dashboard?

**Comment by Zales0123** [comment]
Hello @itinance, did you run Sylius fixtures before opening a page? `docker-compose exec php bin/console sylius:fixtures:load --no-interaction`

**Comment by mcfinley** [comment]
Hey @itinance ! That should be `sylius:sylius` according to docs https://docs.sylius.com/en/latest/book/customers/admin_user.html?highlight=admin
