### ISSUE TITLE
Javascript errors in admin after updating to 1.6

### ISSUE THREAD

**Issue by pocky** [Sylius/Sylius-Standard#367]
Hello,

I updated my Sylius from 1.4.x to 1.6 yesterday and I have two errors in admin with javascript (CSS works fine). I do not know if I've missed something in my updates. `node_modules` is up to date. I think there is a problem with javascript import but I do not know how to debug (JS is not my best friend :D).

Thanks for your time

![image](https://user-images.githubusercontent.com/204451/64270889-8ea9f080-cf3c-11e9-8577-6c2ba2feddf3.png)

![image](https://user-images.githubusercontent.com/204451/64270931-ae411900-cf3c-11e9-8d27-8f0c274e9e86.png)

**Comment by songecko** [comment]
Did you try removing the package lock and the `node_modules` folder?

**Comment by pocky** [comment]
@songecko Thanks a lot. Problem was in yarn.lock \o_
