### ISSUE TITLE
database connection 

### ISSUE THREAD

**Issue by idir-s** [Sylius/Sylius-Standard#370]
Hi everyone , I create a project like that "git clone https://github.com/Sylius/Sylius-Standard.git my-project"

I want to create my custom database. I modified docker-compose.yml

DATABASE_URL=mysql://root:nopassword@mysql/custom_database
.....
  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=custom_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"

But when I run "docker-compose run php php bin/console sylius:install" I have this error :

"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve "

Any idea ?

Thank you

**Comment by Zales0123** [comment]
Hello @idir-s, I've just checked it out and it worked for me with no problems. From the exception that you get, I guess it's not strictly related to Sylius... Btw, you should probably try our [Slack](http://sylius.com/slack), we have a very active community which will probably be able to help you with your problems. Good luck :) 🖖

**Comment by idir-s** [comment]
Thank you, I will send my question on slack

**Comment by Zales0123** [comment]
I'll close the issue then, feel free to reopen if you find some bug in our configuration that needs to be fixed 🚀
