### ISSUE TITLE
Docker 502 Bad Gateway

### ISSUE THREAD

**Issue by RSalo** [Sylius/Sylius-Standard#371]
Hi. I trying to run application through docker-compose and getting exception:
> nginx_1    | 2019/09/16 23:46:10 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "127.0.0.1"

Fresh install from composer.

**Comment by RSalo** [comment]
Solved

**Comment by ikakarov** [comment]
How i have same problem.

**Comment by RSalo** [comment]
> How i have same problem.

just waited when all migrations will completed. this takes long time...
