### ISSUE TITLE
"not supported by platform" while "installing" on a fresh Debian 10/Percona stack

### ISSUE THREAD

**Issue by Zaelyth** [Sylius/Sylius-Standard#407]
Before anything, thanks for Sylius, it has been a joy to develop with.

I've been using the docker stack locally without any issue but for production, I was thinking on skipping docker to remove any unnecessary overhead for my usecase.

But when I launch the sylius:install command, I end up with the following error :
```Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.```

I tried to reproduce the docker-compose ecosystem with PHP7.3, Percona 5.7 and Debian 10.

I've never had this issue on the docker side. Any idea ?

I've seen on some Doctrine issues that it was a mysql implementation problem but how would it work on the docker-compose side then ?

**Comment by lchrusciel** [comment]
Hey!

Your problem may be connected to the database of your choice, maybe some version drift between docker and your server instance? 

Anyway, I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html
