### ISSUE TITLE
[bug] in @CmfCreateBundle/Resources/public/vendor/* not found in standard edition

### ISSUE THREAD

**Issue by mrcmorales** [Sylius/Sylius-Standard#42]
Hi,

I installed the standard edition with this command:
composer create-project -s dev sylius/sylius-standard acme

I can enter with anonymous user but if I loggin with admin I get this error:

An exception has been thrown during the compilation of a template ("Unable to find file "@CmfCreateBundle/Resources/public/vendor/create/lib/jquery-htmlclean/jquery.htmlClean.js".") in "CmfCreateBundle::includejsfiles-hallo.html.twig".

How I can resolve it ?

Thanks!

**Comment by Koc** [comment]
this issue is still unresolved...

**Comment by pjedrzejewski** [comment]
CMFCreateBundle is no longer supported out of the box. Sorry! :(

**Comment by Koc** [comment]
But it is impossible to use Sylius out of the box. I've installed standard edition and sign in as admin and after this got 500 error page. It is not good
