### ISSUE TITLE
 how to Sylius deployment on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by muratsac** [Sylius/Sylius-Standard#420]
Hi everyone,

I have a AWS Elastic Beanstalk environment.

How should `.ebextensions` configurations be to deployment without Docker.

I'm sorry if I asked the question in the wrong place.

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

All these places would be better to ask your question. 

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

**Comment by muratsac** [comment]
Hi again, 

I solved this issue : https://github.com/muratsac/sylius-aws-deploy

**Comment by lchrusciel** [comment]
Nice! You should definitely share it somewhere, so people can use it and perhaps contribute something. I totally recommend twitter and our slack for that :)
