### ISSUE TITLE
Fresh install trouble

### ISSUE THREAD

**Issue by marcoooo** [Sylius/Sylius-Standard#43]
Just installed newly sylius-standard edition. Worked well until trying to log to administration juste after install, and by the way after adding a user with role SYLIUS_ROLE_ADMIN via command line (never mentionned in documentation)

> An exception has been thrown during the rendering of a template ("Currency "EUR" is not available.") 
> in SyliusWebBundle:Backend/Dashboard:main.html.twig at line 34.

Then trying to fix this I executed : 
> app\console sylius:currency:import open_exchange_rates

Got this error 
>  [InvalidArgumentException]                             
>  "OER_APP_ID" must be set in order to use OERImporter.  
  
It doesn't matter, I think I forgot to setup  sylius.currency_importer.open_exchange_rates:
But I'm stucked here, still getting this error even if 
- Succesfully registered to open https://openexchangerates.org/
- got my app_id and put it in parameters.yml

> sylius.currency_importer.open_exchange_rates:
>       app_id: MyAPPID

But still getting the error, I might miss something in setting service parameters
Dumped the content of $options passed to the configure($options) function and got this result 
> array(1) {
>  [0] =>
>  array(1) {
>    'app_id' =>
>    string(32) "MyAPPID"
>  }
>}

The array contains the key but at the wrong level, how can I fix this by configuration ? Or by code in Importer, should I fix it and make a pull request ?

Thanxs a lot.

PS : May be you should find a way to put online a documentation on 'how to make first install work', I could write a paper on my install if it might help. 

Marc

**Comment by zloyded** [comment]
Same issue.

**Comment by armababy** [comment]
It appears it wont work with custom currency on first install.
You have to go back to ``app/config/parameters.yml``and change EUR to USD

Also if you have no Intl extension you might change en_US locale to just en

**Comment by michalmarcinkowski** [comment]
Fixed.
