### ISSUE TITLE
[Docker] Upgrade to PHP 7.4

### ISSUE THREAD

**Issue by YaatSuka** [Sylius/Sylius-Standard#437]
Hello,

I'm currently working on a project based on Sylius and downloaded with Docker.

I have checked out on the 1.8 version (which support PHP 7.4) and, for some reasons, I need to upgrade my PHP version to 7.4.

Unfortunately, after changing and pulling the appropriated docker image, updating the version in the Dockerfile and run a `docker-compose build`, I still have issues because several parts of the Dockerfile are deprecated with this PHP version.

Does anyone know how to fix that?

**Comment by alexispe** [comment]
Hello,  
I remember that you have to at least replace this :
`
docker-php-ext-configure gd --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include --with-webp-dir=/usr/include --with-freetype-dir=/usr/include/; \
`

To this : 
`
docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-webp=/usr/include --with-freetype=/usr/include/; \
`


Can you give errors?

**Comment by alexispe** [comment]
Maybe this can help you : https://github.com/Sylius/Sylius-Standard/pull/391/commits/1658a57fda6627818619ec47ffc37c9e85ba94e4

**Comment by olimination** [comment]
Checkout also: https://github.com/Sylius/Sylius-Standard/pull/536

**Comment by lchrusciel** [comment]
Hey folks, this should be already fixed on the master branch. We will probably release a new Sylius-Standard in the nearest days.
