### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius-Standard#438]
I have the error below on fresh install:

Uncaught Doctrine\ORM\Mapping\MappingException: Cannot find a field on 'Sylius\Component\Core\Model\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exist or an association exists but it has multiple join columns.

**Comment by lchrusciel** [comment]
Hey @SylvanoTombo,

Thanks a lot for submitting an issue. However, it was already submitted https://github.com/Sylius/Sylius/issues/11970, and fixed in https://github.com/Sylius/Sylius/pull/11972. We just need to tag new patch releases. As a workaround, you may add conflict to `"symfony/doctrine-bridge": "4.4.16"` in your app.

**Comment by SylvanoTombo** [comment]
@lchrusciel , thanks for response..I changed but i got a new error:

Problem 1
    - Installation request for sylius/plugin-skeleton No version set (parsed as 1.0.0) -> satisfiable by sylius/plugin-skeleton[No version set (parsed as 1.0.0)].
    - symfony/doctrine-bridge v4.4.16 conflicts with sylius/plugin-skeleton[No version set (parsed as 1.0.0)].
    - Installation request for symfony/doctrine-bridge v4.4.16 -> satisfiable by symfony/doctrine-bridge[v4.4.16].

**Comment by lchrusciel** [comment]
Are these issues related to Plugin Skeleton? Have you resolved your issue already?

**Comment by SylvanoTombo** [comment]
Hi, 
Yeah..my bad..i did it the wrong way..I put in composer.json :
```
{
   "conflicts": {
        "symfony/doctrine-bridge" : "<4.4.16"
    }
}
```
when i had to do it like this:
```
{
   "require": {
        "symfony/doctrine-bridge" : "<4.4.16"
    }
}
```
