### ISSUE TITLE
Broken installation

### ISSUE THREAD

**Issue by nickbass72** [Sylius/Sylius-Standard#477]
Running composer create-project outputs following error:

PHP CodeSniffer Config installed_paths set to ../../slevomat/coding-standard
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-doctrine: installed
> phpstan/phpstan-webmozart-assert: installed
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In FilterExtension.php line 22:
!!                                                                                 
!!    Warning: Declaration of Sylius\Bundle\CoreBundle\Twig\FilterExtension::filt  
!!    er($path, $filter, array $config = Array, $resolver = NULL) should be compa  
!!    tible with Liip\ImagineBundle\Templating\FilterExtension::filter($path, $fi  
!!    lter, array $config = Array, $resolver = NULL, $referenceType = Symfony\Com  
!!    ponent\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_URL)                
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Composer: 2.0.8
PHP: 7.4.13

**Comment by Zales0123** [comment]
Hi @nickbass72! Fix is already there https://github.com/Sylius/Sylius/pull/12187, we will release the patched version asap :)

**Comment by nickbass72** [comment]
@Zales0123 Thanks for the fast response! :)

**Comment by Zales0123** [comment]
No problem, the tag is already there :) https://github.com/Sylius/Sylius/releases/tag/v1.8.7
