### ISSUE TITLE
 Attempted to load class "SecurityCheckerCommand" from namespace "SensioLabs\Security\Command".

### ISSUE THREAD

**Issue by akrick** [Sylius/Sylius-Standard#481]
In getSecurityCheckerCommandService.php line 9:

  Attempted to load class "SecurityCheckerCommand" from namespace "SensioLabs\Security\Command".

the composer.json already required the package, what's going on with that?

**Comment by lchrusciel** [comment]
The recommendation would be to either config (as done in https://github.com/Sylius/Sylius-Standard/pull/427) or add `sensiolabs/security-checker` to dependencies as @gdarquie suggested.
