### ISSUE TITLE
No identifier defined "Sylius\Bundle\ApiBundle\Command\RegisterShopUser"

### ISSUE THREAD

**Issue by arnaudbagnis** [Sylius/Sylius-Standard#493]
Error when i build php Dockerfile 

`Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the prod environment with debug                      
!!   // false                                                                       
!!  
!!  
!!  In FileLoader.php line 180:
!!                                                                                 
!!    No identifier defined "Sylius\Bundle\ApiBundle\Command\RegisterShopUser". Y  
!!    ou should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]  
!!    " on the property identifying the resource." in . (which is being imported   
!!    from "/srv/sylius/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resource  
!!    s/config/routing.yml"). Make sure there is a loader supporting the "api_pla  
!!    tform" type.                                                                 
!!                                                                                 
!!  
!!  In IdentifiersExtractor.php line 65:
!!                                                                                 
!!    No identifier defined "Sylius\Bundle\ApiBundle\Command\RegisterShopUser". Y  
!!    ou should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]  
!!    " on the property identifying the resource."                                 
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-install-cmd
`

**Comment by demon-tdr** [comment]
Same problem here. I followed the installation instructions (https://docs.sylius.com/en/latest/book/installation/installation.html#initiating-a-new-sylius-project) in a clean environment with:

- PHP 7.4.14
- MariaDB 10.5.8
- Nginx 1.18.0

This is the output:

```
$ composer create-project sylius/sylius-standard acme
Creating a "sylius/sylius-standard" project at "./acme"
Installing sylius/sylius-standard (v1.8.6)
  - Downloading sylius/sylius-standard (v1.8.6)
  - Installing sylius/sylius-standard (v1.8.6): Extracting archive
Created project in /var/www/acme
Loading composer repositories with package information
Updating dependencies
Lock file operations: 262 installs, 0 updates, 0 removals
  - Locking api-platform/core (v2.6.0)
  - Locking behat/behat (v3.8.1)
  - Locking behat/gherkin (v4.6.2)
  - Locking behat/mink-selenium2-driver (v1.4.0)
  
...
...
...
  
Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your Javascript dependencies!
Run composer recipes at any time to see the status of your Symfony recipes.

PHP CodeSniffer Config installed_paths set to ../../slevomat/coding-standard
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-doctrine: installed
> phpstan/phpstan-webmozart-assert: installed
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In FileLoader.php line 180:
!!                                                                                 
!!    No identifier defined "Sylius\Bundle\ApiBundle\Command\RegisterShopUser". Y  
!!    ou should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]  
!!    " on the property identifying the resource." in . (which is being imported   
!!    from "/var/www/acme/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resour  
!!    ces/config/routing.yml"). Make sure there is a loader supporting the "api_p  
!!    latform" type.                                                               
!!                                                                                 
!!  
!!  In IdentifiersExtractor.php line 65:
!!                                                                                 
!!    No identifier defined "Sylius\Bundle\ApiBundle\Command\RegisterShopUser". Y  
!!    ou should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]  
!!    " on the property identifying the resource."                                 
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by arnaudbagnis** [comment]
I resolve my issue thanks to [here ](https://stackoverflow.com/questions/65869174/sylius-install-crashes-because-no-identifier-defined/65886285#65886285)

**Comment by demon-tdr** [comment]
Thank you @arnaudbagnis it worked!

**Comment by lchrusciel** [comment]
All released versions should already have a conflict with AP 2.6
