### ISSUE TITLE
`docker-compose` pull error

### ISSUE THREAD

**Issue by bram-pkg** [Sylius/Sylius-Standard#552]
When I run `docker-compose pull` it gives the following error:

```
ERROR: for php  unauthorized: access to the requested resource is not authorized

ERROR: for nginx  unauthorized: access to the requested resource is not authorized

ERROR: for nodejs  unauthorized: access to the requested resource is not authorized
```

**Comment by mantans** [comment]
i have tried using docker login quay.io without success

**Comment by mantans** [comment]
Solved following these steps:

- Updated Dockerfile, docker-compose.yml, placed docker-healthcehck.sh and symfony.lock inside docker/php folder using these:  #1658a57
- From Dockerfile l79 removed composer.lock from copying
- docker-compose up -d

Once completed wait 10/15 minutes and the php container become healthy and everything work

**Comment by tonicospinelli** [comment]
I worked to decrease this long waiting time until the PHP container is ready. I invite you to test this changes #568 in your local environment

**Comment by mantans** [comment]
> 
> 
> I worked to decrease this long waiting time until the PHP container is ready. I invite you to test this changes #568 in your local environment

Thank you, i ll give it a try asap, generally that delay happens during the first deploy, so i will try it from scratch.

**Comment by Ferror** [comment]
We made it work :)
