### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by MeTaLiKiD** [Sylius/Sylius-Standard#57]
Hi,

I'm developping an e-commerce website using Sylius.

I don't understand how to edit the design for user interaction like login, registration...

Because I don't know if I have to inherit the FOSUserBundle or to do something else?
I didn't find a SyliusUserBunlde.

Thanks for the help.

**Comment by michalmarcinkowski** [comment]
From now you have SyliusUserBundle and should inhert from it's entities.
