### ISSUE TITLE
sylius:install: Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time

### ISSUE THREAD

**Issue by joostvdspeld** [Sylius/Sylius-Standard#58]
Hi,

I'm installing sylius-standard with composer.

When i run the cmd: $ app/console sylius:install, Step 3 of 4 Shop configuration, return this error:

[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: ini_set(): A session is active. You cannot change the session modu
le's ini settings at this time

Extra: php.ini -> session.auto_start = 0

How can i fix this?

Thanks.

**Comment by michalmarcinkowski** [comment]
It has been fixed already (https://github.com/Sylius/Sylius-Standard/pull/71).
