### ISSUE TITLE
Installing sylius-standard from composer gives ParameterNotFoundException

### ISSUE THREAD

**Issue by mariuseliassen** [Sylius/Sylius-Standard#59]
After entering the sylius config (sylius.database.driver <- ... -> sylius.order.pending.duration) the next step gives a ParameterNotFoundException
```
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "sylius.currency_importer.european_central_bank" has a dependency on a non-existent parameter "sylius.currency_importer.ecb.base_currency".

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

[RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command.
```

Command that was run is:
```
$ composer create-project -s dev sylius/sylius-standard sylius-standard
```

**Comment by mariuseliassen** [comment]
One solution is to manually enter

```
sylius.currency_importer.ecb.base_currency: EUR
```
into app/config/parameters.yml - obv you can replace EUR with whatever you want here.

**Comment by igormukhingmailcom** [comment]
@mariuseliassen 
You need better add this parameter to `app/config/parameters.yml.dist`.
Otherwise this parameter will be removed after next `composer update` or `composer install`.

**Comment by michalmarcinkowski** [comment]
Not an issue anymore.
