### ISSUE TITLE
web/media should be writable and shared in deploy.rb

### ISSUE THREAD

**Issue by liviucmg** [Sylius/Sylius-Standard#62]
Hi all,

Product images are generated on-the-fly using LiipImagineBundle inside the `web/media` folder, but this folder is not configured properly inside app/deploy.rb. It needs to be both writable (so that the images can be generated) and shared (so that the files persist from one deployment to another).

Will you accept a PR for this?

Thanks.

**Comment by pjedrzejewski** [comment]
@liviucmg Sorry for late reply, but absolutely yes!

**Comment by liviucmg** [comment]
@pjedrzejewski Awesome, hope to send out a PR later today.
