### ISSUE TITLE
 Allowed memory size 

### ISSUE THREAD

**Issue by Fabiomad85** [Sylius/Sylius-Standard#620]
Executing the command docker-compose up, I got this error 

`2021-11-12T08:00:33.308261Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2021-11-12T08:00:33.308342Z 0 [Note] IPv6 is available.
2021-11-12T08:00:33.308350Z 0 [Note]   - '::' resolves to '::';
2021-11-12T08:00:33.308362Z 0 [Note] Server socket created on IP: '::'.
2021-11-12T08:00:33.324682Z 0 [Note] Event Scheduler: Loaded 0 events
2021-11-12T08:00:33.324845Z 0 [Note] mysqld: ready for connections.
Version: '5.7.35-38'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  Percona Server (GPL), Release 38, Revision 3692a61
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
Done in 18.00s.
Waiting for PHP to be ready...

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 268435464 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 84

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.c`

I googled some solution like `COMPOSER_MEMORY_LIMIT=-1`, but it is already implemented.

Any Sudgestion, please? thanks

**Comment by lchrusciel** [comment]
Hey Fabiano,
can you check with the current Sylius-Standard master? You may use following script:
```
composer create-project --stability=dev sylius/sylius-standard:dev-master
```

**Comment by Fabiomad85** [comment]
I solved adding COMPOSE_MEMORY_LIMIT=-1  inside the file docker-entrypoint.php
