### ISSUE TITLE
Cannot install Sylius 1.10.5 in PHP 8

### ISSUE THREAD

**Issue by delyriand** [Sylius/Sylius-Standard#626]
With the Sylius-Standard 1.10.0, in PHP 8, we cannot install Sylius 1.10.5:

```
 php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 07:35:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
```

```
composer create-project --prefer-dist --no-scripts --no-progress sylius/sylius-standard sylius "~1.10.0"
Creating a "sylius/sylius-standard" project at "./sylius"
Installing sylius/sylius-standard (v1.10.0)
  - Installing sylius/sylius-standard (v1.10.0): Extracting archive
Created project in /private/tmp/sylius
Loading composer repositories with package information
Updating dependencies
Lock file operations: 241 installs, 0 updates, 0 removals
...
  - Locking sylius/sylius (v1.10.4)
...
```

**Comment by delyriand** [comment]
cf Sylius/Sylius#13323

**Comment by Zales0123** [comment]
Hello @delyriand! Can you, please, check it out one more time? I've just tried it with the exact command as you provided, and Sylius 1.10.5 was installed with no problems 🤔

**Comment by jpineau-dev** [comment]
Hello @Zales0123, 

I just tried to install Sylius 1.10 with the command composer `create-project --prefer-dist --no-scripts --no-progress sylius/sylius-standard sylius "~1.10.0"` and no error is displayed, however when I continue the installation steps with the command `php bin/console sylius: install` the error is displayed again :

```php
php bin/console sylius:install

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                                              
The service "security.authorization_checker" has a dependency on a non-existent service "security.authenti  
cation_manager". Did you mean one of these: "security.authorization_checker", "security.authentication_uti  
ls", "security.authentication.manager", "security.authentication.guard_handler"?
```

I am using PHP 8.0 and Composer 2.1.14

**Comment by Zales0123** [comment]
Hi @jpineau-dev 👋 It's another problem, we're already working on this (take a look at [this issue](https://github.com/Sylius/Sylius-Standard/issues/630))

**Comment by delyriand** [comment]
Hi @Zales0123! You're right… I can't reproduce the initial problem.  
Now, the 1.10.5 is installed, but i dont known why. It's the magic of dependencies.

**Comment by Zales0123** [comment]
We all know programming is a kind of magic 😄 🪄  Nevertheless, it's good it works now, closing an issue then 🚀 Cheers
