### ISSUE TITLE
docker fails on python installation 

### ISSUE THREAD

**Issue by bbougon** [Sylius/Sylius-Standard#628]
Description:
When executing `docker-compose up`, build step fails with 
```
#10 1.240 ERROR: unable to select packages:
#10 1.315   python (no such package):
#10 1.315     required by: .build-deps-20211124.213805[python]
```

Step to reproduce: perform a `docker-compose up` on a fresh git repository clone (and after doing some php composer update to avoid the composer.lock issue)

Actual result: build fails with above result

Expected result: docker build image works

NB: this is due to a bad apk add command which target `pyhton`instead of `python3` line 120 in `Dockerfile`

**Comment by vasilvestre** [comment]
Fixed by https://github.com/Sylius/Sylius-Standard/pull/621
