### ISSUE TITLE
Behat - `sylius.behat.context.hook.doctrine_orm` context class not found and can not be used.

### ISSUE THREAD

**Issue by Fabiomad85** [Sylius/Sylius-Standard#629]
I tried to write down my own test for an sylius 1.10 instance.

I executed the command: `APP_ENV=test ./vendor/bin/behat`

then I get this error `sylius.behat.context.hook.doctrine_orm context class not found and can not be used.`

I dig inside the file on line44
/vendor/behat/behat/src/Behat/Behat/Context/Environment/UninitializedContextEnvironment.php

this is the stacktrace

`Exception trace:
  at /srv/sylius/vendor/behat/behat/src/Behat/Behat/Context/Environment/UninitializedContextEnvironment.php:44
 Behat\Behat\Context\Environment\UninitializedContextEnvironment->registerContextClass() at /srv/sylius/vendor/behat/behat/src/Behat/Behat/Context/Environment/Handler/ContextEnvironmentHandler.php:91
 Behat\Behat\Context\Environment\Handler\ContextEnvironmentHandler->buildEnvironment() at /srv/sylius/vendor/friends-of-behat/symfony-extension/src/Context/Environment/Handler/ContextServiceEnvironmentHandler.php:77
 FriendsOfBehat\SymfonyExtension\Context\Environment\Handler\ContextServiceEnvironmentHandler->buildEnvironment() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Environment/EnvironmentManager.php:69
 Behat\Testwork\Environment\EnvironmentManager->buildEnvironment() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php:67
 Behat\Testwork\Tester\Runtime\RuntimeExercise->test() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:73
 Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php:80
 Behat\Testwork\Ordering\OrderedExercise->test() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:149
 Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108
 Behat\Testwork\Tester\Cli\ExerciseController->execute() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php:63
 Behat\Testwork\Cli\Command->execute() at /srv/sylius/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /srv/sylius/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /srv/sylius/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /srv/sylius/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:124
 Behat\Testwork\Cli\Application->doRun() at /srv/sylius/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /srv/sylius/vendor/behat/behat/bin/behat:34
`

I would like to make a simple test to get the homepage of my ecommerce any ideas?

**Comment by Prometee** [comment]
Hi @Fabiomad85!

It's been a while seen you posted this, I hope you found what was the root of the issue.

I had the same error and figured out why, for those who pass by, here is how to fix the issue:

1. Check you are using the `APP_ENV=test`
2. Check that you are importing Sylius Behat services definitions only for this same environnement, usually you will found an import statement here : `config/services_test.yaml`
    ```yaml
    imports:
      - { resource: '../vendor/sylius/sylius/src/Sylius/Behat/Resources/config/services.xml' }
    ```
3. retry running Behat and it should work fine.
