### ISSUE TITLE
Cannot install Sylius from CLI

### ISSUE THREAD

**Issue by cibolog** [Sylius/Sylius-Standard#630]
The commands provided at `README.md` fail at `php composer.phar create-project sylius/sylius-standard project`
Ubuntu 20.04, PHP 7.4

```
PHP CodeSniffer Config installed_paths set to ../../slevomat/coding-standard
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-doctrine: installed
> phpstan/phpstan-webmozart-assert: installed
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "security.authorization_checker" has a dependency on a non-exis  
!!    tent service "security.authentication_manager". Did you mean one of these:   
!!    "security.authorization_checker", "security.authentication_utils", "securit  
!!    y.authentication.manager", "security.authentication.guard_handler"?          
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by merbekta** [comment]
Hi, did you find a solution for this error? i have the same problem

**Comment by merbekta** [comment]
> 

Did you find a solution for this error? i have the same problem

**Comment by Zales0123** [comment]
Hello @cibolog and @merbekta, I think this PR https://github.com/Sylius/Sylius-Standard/pull/631 will solve this issue 🖖

**Comment by merbekta** [comment]
> Hello @cibolog and @merbekta, I think this PR #631 will solve this issue 🖖

Hey @Zales0123 , thanks. You are my hero :)  I used 5.3 instead of symfony 5.4 and my problem was solved

**Comment by Zales0123** [comment]
Great :) I had a quick discussion with @lchrusciel and (as you can see on the linked PR), we will try to introduce proper Symfony 5.4 support to Sylius 1.10 as well (not only upcoming 1.11), so this will not be an issue in the nearest future anymore 💃 Cheers 🖖

**Comment by merbekta** [comment]
> Great :) I had a quick discussion with @lchrusciel and (as you can see on the linked PR), we will try to introduce proper Symfony 5.4 support to Sylius 1.10 as well (not only upcoming 1.11), so this will not be an issue in the nearest future anymore 💃 Cheers 🖖

thank you for your work :)
