### ISSUE TITLE
sylius:install:setup throws NoSuchMetaDataException after entering locale

### ISSUE THREAD

**Issue by goemaere** [Sylius/Sylius-Standard#64]
This happens on (new) installs on my local vagrant box, but also on my linux dev server. I only have this problem with sylius-standard (current master). I am not having this problem with sylius/sylius:0.14.0

```
  [Symfony\Component\Validator\Exception\NoSuchMetadataException]
  The class or interface "en_US" does not exist.
```

Edit: because there is no composer.lock file available, composer is installing Symfony 2.7. The Symfony/Validator does not seem to be compatible with the current installationscript. If I add Symfony ~2.3.30 in my composer.json file the installer works just fine.

**Comment by iBet7o** [comment]
same problem https://github.com/Sylius/Sylius/issues/2810

**Comment by taliah** [comment]
If you just type in 'en' instead of 'en_US' it'll work.
