### ISSUE TITLE
Remove `composer.lock` from `.gitignore`

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius-Standard#665]
The `.gitignore` file, that is currently shipped, references `composer.lock`. This is very easy to miss after cloning the repo, and might end up with uncommitted `composer.lock` in actual downstream projects, at least initially.
Perhaps there is a better way to prevent `composer.lock` from being committed here, while not excluding it from downstream projects by default?

**Comment by vvasiloi** [comment]
Maybe a Composer script on `post-create-project-cmd`? Can't think of anything else.

**Comment by vvasiloi** [comment]
Maybe a Git hook.

**Comment by rimas-kudelis** [comment]
`post-create-project-cmd` would only work with when `composer create-project` is used, which, at least for me, is not usually the case (although maybe I should get used to using it instead of just `git clone`'ing the repo I need).

A Git hook would be a more universal approach from the end-user point of view, but I guess it would be a bit more annoying for the maintainers.

**Comment by artyuum** [comment]
> This is very easy to miss after cloning the repo, and might end up with uncommitted composer.lock in actual downstream projects

I'm trying Sylius for the first time and that's exactly what happened. A co-worker added a package and the changes to the  composer.lock file didn't get commited so it broke my instance as doing composer install didn't detect that there is a new dependency to install.

**Comment by diimpp** [comment]
@rimas-kudelis @jakubtobiasz hi, looks like issue can be closed after last PR

**Comment by jakubtobiasz** [comment]
Yup, thanks for reminding :).
