### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by cjuhong** [Sylius/Sylius-Standard#67]
Clearing the cache for the dev environment with debug true
Download or update create
Download or update ckeditor
PHP Fatal error:  Class 'Sylius\Bundle\CoreBundle\Kernel\Kernel' not found in /home/jeremy/vhost/lettuce/app/AppKernel.php on line 6
PHP Stack trace:
PHP   1. {main}() /home/jeremy/vhost/lettuce/app/console:0
PHP   2. require_once() /home/jeremy/vhost/lettuce/app/console:7
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception

                                                                                
  [RuntimeException]                                                            
  An error occurred when executing the "'assets:install '\''web'\'''" command.  
                                                                                

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

**Comment by michalmarcinkowski** [comment]
Shouldn't be an issue anymore.

**Comment by ibasaw** [comment]
What is the fix for this one ? @michalmarcinkowski
