### ISSUE TITLE
Elasticsearch configuration

### ISSUE THREAD

**Issue by ImmRanneft** [Sylius/Sylius-Standard#68]
Hey all.
Just interesting how can I configure my sylius-standart based application to user elasticsearch. README and google can't answer this question at all, cause they have quite little information. Maybe somebody can figure me out how config.yml have to look to work with elasticsearch?

**Comment by cjuhong** [comment]
+1

**Comment by michalmarcinkowski** [comment]
The ElasticSearch support will be provided by https://github.com/Lakion/SyliusElasticSearchBundle as extension :wink:
