### ISSUE TITLE
Missing CatalogPromotion entities

### ISSUE THREAD

**Issue by benjaminmal** [Sylius/Sylius-Standard#729]
When installing Sylius via `composer create-project sylius/sylius-standard acme`, the recommended way, all new `CatalogPromotion*` extended entities are missing in `src/Entity/Promotion` folder. Since they exist with `v1.11` and are entities (mapped by Doctrine etc), why are they not in this folder? Since every other entities are extended from `CoreBundle` or its own component, I don't see why. Are they missing? I can submit a PR if needed.

**Comment by Zales0123** [comment]
Hello @benjaminmal, we've already fixed it with https://github.com/Sylius/Sylius-Standard/pull/806. I will release a new version of Sylius-Standard soon, so it would not be a problem anymore 🖖
