### ISSUE TITLE
[RFC] - upgrading sylius/standar and database migrations

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius-Standard#74]
Hi all

Is there any recommended way how run migrations after upgrading the sylius/sylius-standard distribution?

I started with 0.14.
After release of 0.15, I changed my composer.json and fired up composer update.

The codebase updated without problem but, my existing database didn't update with migrations from main sylius package.

The first problem is that with sylius/sylius-standard you wont have migrations_versions table at all in your DB, so even if I configure doctrine migrations to look in vendor/sylus/sylius/app/migrations directory with the correct namespace, doctrine will try to run every migration there.

Even tho this is fixed with this PR sylius/sylius#3205, if the config would point to vendor/sylius/sylius/migrations.
There is still the issue about where to point migrations.yml by default:

* app/DoctrineMigration - users application folder
* vendor/sylius/sylius/app/migrations

If anyone got any pointers experience with cross bundle migrations, share.

**Comment by michalmarcinkowski** [comment]
We will discuss the migrations and organize them in the v0.16. Probably all migrations will be put in the CoreBundle and we will add `sylius:migrate` command which will run them. So after `composer update sylius/sylius` you will just run the command and the database will be updated to the newest Sylius version.

**Comment by michalmarcinkowski** [comment]
The discussion will be continued there https://github.com/Sylius/Sylius/issues/3303

**Comment by nakashu** [comment]
thanks michal
