### ISSUE TITLE
Installing on PHP7 Vagrant box

### ISSUE THREAD

**Issue by BartDuch** [Sylius/Sylius-Standard#75]
First issue I ran into was, at the end of ```php app/console sylius:install ```:
```
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap

Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/sylius/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 28
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception 
```

Fixed this by deleting this line:
https://github.com/Sylius/Sylius-Standard/blob/master/app/autoload.php#L12
Like suggested where: https://github.com/doctrine/phpcr-odm/issues/649

That fixed the problem, but now it's extremly slow, half of the time I get:
```
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/sylius/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php on line 192
```

[UPDATE]
This helped a lot these optimizations:
http://by-examples.net/2014/12/09/symfony2-on-vagrant.html

The page load is now less then a second

I do see quite some deprecated functions, most of them in Twig:

    DEPRECATED - The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.  +
    DEPRECATED - Calling the Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead. (4x)  +
    DEPRECATED - The Symfony\Component\OptionsResolver\OptionsResolver::setOptional method is deprecated since version 2.6 and will be removed in 3.0. Use the setDefined() method instead. (2x)  +
    DEPRECATED - Sylius\Bundle\CoreBundle\Form\Type\CartItemType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.  +
    DEPRECATED - Sylius\Bundle\VariationBundle\Form\Type\VariantMatchType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.  +
    DEPRECATED - Calling the Symfony\Component\OptionsResolver\OptionsResolver::addAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead. (6x)  +
    DEPRECATED - Sylius\Bundle\VariationBundle\Form\Type\OptionValueChoiceType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.  +
    DEPRECATED - The Symfony\Component\Form\Extension\Core\ChoiceList\ObjectChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.  +
    DEPRECATED - The Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\ArrayChoiceList instead.  +
    DEPRECATED - The Symfony\Component\Form\Extension\Core\View\ChoiceView class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\View\ChoiceView instead.  +
    DEPRECATED - The "choice_list" option is deprecated since version 2.7 and will be removed in 3.0. Use "choice_loader" instead.  +
    DEPRECATED - The Twig render tag was deprecated in version 2.2 and will be removed in version 3.0. Use the Twig render function instead.  +
    DEPRECATED - The Symfony\Component\Routing\Route::getPattern method is deprecated since version 2.2 and will be removed in 3.0. Use the getPath() method instead. (5x)  +
    DEPRECATED - Using an instance of "Twig_SimpleFunction" for filter "0" is deprecated. Use Twig_SimpleFilter instead.  +
    DEPRECATED - The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.  +
    DEPRECATED - The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "sm_can" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - The Twig_Filter_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
    DEPRECATED - The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Filter_Function" for filter "cmf_embed_blocks" is deprecated. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "createphp_attributes" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "createphp_content" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "knp_menu_get" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "knp_menu_render" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - The Twig_Filter_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "serialize" is deprecated. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "serialization_context" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "desc" is deprecated. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "meaning" is deprecated. Use Twig_SimpleFilter instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "pagerfanta" is deprecated. Use Twig_SimpleFunction instead.  +
    DEPRECATED - Using an instance of "Twig_Function_Method" for function "pagerfanta_page_url" is deprecated. Use Twig_SimpleFunction instead.  +

**Comment by BartDuch** [comment]
I see that most of the time is spend by Twig:
```
Twig Stats
Total Render Time
including sub-requests rendering time	
35503 ms
Template Calls	
23
Block Calls	
53
Macro Calls	
15
```
Also see a lot of deprecated functions are been called:
```
DEPRECATED - The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.  +
DEPRECATED - Calling the Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead. (2x)  +
DEPRECATED - Using an instance of "Twig_SimpleFunction" for filter "0" is deprecated. Use Twig_SimpleFilter instead.  +
DEPRECATED - The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.  +
DEPRECATED - The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "sm_can" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - The Twig_Filter_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
DEPRECATED - The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Filter_Function" for filter "cmf_embed_blocks" is deprecated. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "createphp_attributes" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "createphp_content" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "knp_menu_get" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "knp_menu_render" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - The Twig_Filter_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "serialize" is deprecated. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "serialization_context" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "desc" is deprecated. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "meaning" is deprecated. Use Twig_SimpleFilter instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "pagerfanta" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Using an instance of "Twig_Function_Method" for function "pagerfanta_page_url" is deprecated. Use Twig_SimpleFunction instead.  +
DEPRECATED - Calling the Symfony\Component\OptionsResolver\OptionsResolver::addAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Use the new signature with a single option instead. (8x)  +
DEPRECATED - The Twig render tag was deprecated in version 2.2 and will be removed in version 3.0. Use the Twig render function instead.  +
DEPRECATED - The Symfony\Component\Routing\Route::getPattern method is deprecated since version 2.2 and will be removed in 3.0. Use the getPath() method instead. (13x)  +
DEPRECATED - The Symfony\Component\OptionsResolver\OptionsResolver::setOptional method is deprecated since version 2.6 and will be removed in 3.0. Use the setDefined() method instead.  +
```

**Comment by pjedrzejewski** [comment]
These Twig depracations are coming from vendor bundles, so they would need to update them.

Maybe it is worth adding a cookbook article pointing to this link http://by-examples.net/2014/12/09/symfony2-on-vagrant.html? What do you think?

**Comment by BartDuch** [comment]
Think this would help a lot of people new to this.

I see you closed, but don't forget about the actual bug reported in the beginning or my post, this was a pretty annoying one to find:

First issue I ran into was, at the end of ```php app/console sylius:install ```:
```
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap

Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/sylius/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 28
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception 
```

Fixed this by deleting this line:
https://github.com/Sylius/Sylius-Standard/blob/master/app/autoload.php#L12
Like suggested where: https://github.com/doctrine/phpcr-odm/issues/649
