### ISSUE TITLE
You have requested a non-existent service "<app_name>.controller.<entity>".

### ISSUE THREAD

**Issue by PurpleBabar** [Sylius/Sylius-Standard#76]
When I want to use that controller in a route, i get the following error : 

You have requested a non-existent service "<app_name>.controller.<entity>".

But when i do php app/console container:debug | grep <app_name>

i see that service declared... Anyone got an idea ?

**Comment by PurpleBabar** [comment]
I had a caching issue, just solved it. Sorry for the post :/

**Comment by pjedrzejewski** [comment]
@PurpleBabar No worries, always report if you have any errors. Questions about "how to do something" should be posted on StackOverflow, but bug reports here. Thank you for closing the issue when fixed, it helps a lot! See you around. :)
