### ISSUE TITLE
Include composer.lock

### ISSUE THREAD

**Issue by moein** [Sylius/Sylius-Standard#77]
Hey guys

I recently came across this project and really appreciate your hard work!

I downloaded your project and noticed that the composer.lock is missing which is pretty normal to have in standard projects. 

I know the project is in the development phase but actually I created this task because I had to increase my memory limit for php to more than 1gb to be able to run composer install.

Cheers

**Comment by michalmarcinkowski** [comment]
Composer.lock added. Thanks for reporting!
