### ISSUE TITLE
Cannot create route [phpcr_odm_path]

### ISSUE THREAD

**Issue by stiffroy** [Sylius/Sylius-Standard#78]
Whenever I am trying to create a route for a page (content), it gives me an error message saying "This value is not valid." But this is a completely new route. I created a page and it said in the Route field "Your content will not appear in frontend if no route is defined" and then when I try to create a route for the page, the error message is given. It is also the same when I try to make a new route.

The profiler gives me this:

![screen shot 2015-10-19 at 02 23 17](https://cloud.githubusercontent.com/assets/13282223/10567658/9d340a6c-760a-11e5-8cda-b23582a08f22.png)

Please help me. I am in a big fix. If I can't find a solution quickly, then I might have to shift to some other application from Sylius which I don't want.

**Comment by pjedrzejewski** [comment]
Hello @stiffroy!

We will try to help. :) Have you run Sylius installer correctly? Try executing ``app/console doctrine:phpcr:repository:init``. It seems like you are missing some default documents in the PHPCR structure "/cms/routes", that's why form is bugged. Let me know if that helps, you can also post this question to StackOverflow with "sylius" tag. Maybe someone else will try to help as well.

**Comment by stiffroy** [comment]
Hi @pjedrzejewski,

Thanks for your reply. After running the console code, I got the bellow response:
```console
Successfully registered system node types.
Executing initializer: CmfBlockBundle
Executing initializer: CmfContentBundle
Executing initializer: CmfMenuBundle
Executing initializer: CmfMediaBundle
```

Here it didn't initialize the ```CmfRoutingBundle```. I think this is a problem of the Symfony Cmf Bundle. But somehow I figured out a solution (don't think if this is the right one). I added a value in the database and cleared the cache. Then it started working as expected. The SQL command would be:

```sql
INSERT INTO `sylius_dev`.`phpcr_nodes` (`id`, `path`, `parent`, `local_name`, `namespace`, `workspace_name`, `identifier`, `type`, `props`, `numerical_props`, `depth`, `sort_order`) VALUES (NULL, '/cms/routes', '/cms', 'routes', '', 'default', 'bc65062e-9b31-41b4-a18e-eef59465edc2', 'nt:unstructured', '<?xml version="1.0" encoding="UTF-8"?>
<sv:node xmlns:mix="http://www.jcp.org/jcr/mix/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:sv="http://www.jcp.org/jcr/sv/1.0" xmlns:rep="internal"><sv:property sv:name="jcr:primaryType" sv:type="Name" sv:multi-valued="0"><sv:value length="15">nt:unstructured</sv:value></sv:property></sv:node>
', NULL, '2', '5');
```

This value is loaded if you use the console command for installing the sample-data ```php app/console sylius:install:sample-data```

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/3967.
