### ISSUE TITLE
Docker build error WL2

### ISSUE THREAD

**Issue by ytilotti** [Sylius/Sylius-Standard#788]
Hi all,

after I run `docker-compose build` on a docker with WSL2 and the last version of master, I have the following issue:
![177110517-b591623e-5ba1-409d-9b58-0642d8bdbb33](https://user-images.githubusercontent.com/5848945/177153562-9acdaa96-eb37-40f8-b28a-7b5805e13008.png)

**Comment by ytilotti** [comment]
Can't assign @Ferror ;)

**Comment by JacquesDurand** [comment]
Hi ! 
I was just about to post the same. It seems that the following is missing in composer.json: 
```json
    "config": {
        "allow-plugins": {
            "symfony/flex": true
        },
```

**Comment by vvasiloi** [comment]
You're right @JacquesDurand. The changes from this PR https://github.com/Sylius/Sylius/pull/14106 should be done here too.
