### ISSUE TITLE
Installer issue with composer - fails doctrine/phpcr-odm

### ISSUE THREAD

**Issue by nslocomotives** [Sylius/Sylius-Standard#79]
Please can you assist i think the composer file in the standard package needs some work, I'm following the steps on your main website to install the standard edition to start my project, i wasn't expecting to have to start fixing issues from the get go.

Ive seen this issue resolved on the Sylius repo by applying this https://github.com/Sylius/Sylius/issues/3595 I applied it locally to my composer file and it then completed the install.  

I have to be honest I've stopped working with Sylius because i struggling with the documentation at the moment, but i may come back to it. 

Nigel.

heres the output i get.

Nigels-iMac:NetBeansProjects nigelsmith$ php -dmemory_limit=-1 /bin/composer create-project sylius/sylius-standard -s dev
Installing sylius/sylius-standard (dev-master 4a2f05e8ab0611de14569f4417242b13621e546f)

Installing sylius/sylius-standard (dev-master master) Cloning master
Created project in /Users/nigelsmith/NetBeansProjects/sylius-standard
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for sylius/sylius 0.16.*@dev -> satisfiable by sylius/sylius[0.16.x-dev].
- sylius/sylius 0.16.x-dev requires doctrine/phpcr-odm ^1.3@rc -> no matching package found.

Potential causes:

A typo in the package name
The package is not available in a stable-enough version according to your minimum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by michalmarcinkowski** [comment]
Should be resolved already.
