### ISSUE TITLE
[Docker Compose] Env vars for host ports

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius-Standard#790]
Add environment variables for all host port mappings.
You would think that `docker-compose.override.yml` would solve this, but the ports configuration array gets merged. 

/cc @Ferror

**Comment by Ferror** [comment]
@vvasiloi do you mean this? https://github.com/Sylius/Sylius-Standard/pull/649

**Comment by vvasiloi** [comment]
@Ferror Yes.

**Comment by Ferror** [comment]
As you see I approved it. Will trigger the Merger Role :)

**Comment by Ferror** [comment]
Merged https://github.com/Sylius/Sylius-Standard/pull/649
