### ISSUE TITLE
Cannot import ressources sylis.yml

### ISSUE THREAD

**Issue by jujusous3** [Sylius/Sylius-Standard#8]
Hi !

I see some fix have been added, so I try to get a fresh install : 

composer create-project -s dev sylius/sylius-standard

I put the informations for parameters.yml, and at the end I've got : 

Cannot import resource "/Users/Juju/Sites/sylius-standard/app/config/sylius.yml" from "/Users/Juju/Sites/sylius-standard/app/config/config.yml". (There is no extension able to load the configuration for "sylius_payum" (in /Users/Juju/Sites/sylius-standard/app/config/sylius.yml). Looked for namespace "sylius_payum", found "sylius_installer", "sylius_order", "sylius_money", "sylius_settings",...etc

Somebody have an idea ?

Thx

**Comment by michalmarcinkowski** [comment]
Not an issue anymore.
