### ISSUE TITLE
docker mysql_random_root_password

### ISSUE THREAD

**Issue by duchnoun** [Sylius/Sylius-Standard#836]
Hi,

idk if it is due to docker version but i need to update :

MYSQL_RANDOM_ROOT_PASSWORD: true => to => MYSQL_RANDOM_ROOT_PASSWORD: "yes"

ERROR: The Compose file './docker-compose.prod.yml' is invalid because:
services.mysql.environment.MYSQL_RANDOM_ROOT_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null

An idea ? 
Thanks

**Comment by duchnoun** [comment]
no body got a response ? thanks :)

**Comment by Ferror** [comment]
You should actually change it to `MYSQL_RANDOM_ROOT_PASSWORD: 1`
