### ISSUE TITLE
Error when creating a new locale in admin panel

### ISSUE THREAD

**Issue by hephaistosthemaker** [Sylius/Sylius-Standard#84]
I created a new "fr" locale in the admin panel (sylius versions 0.16.0-dev) and "French" appeared in "Code" instead of the selected "fr" and nothing appear in "name".
When I goto the channel admin page for example, twig output an error because there is no __tostring for locale "French".
After replacing "French" by "fr" in "Code" column directly in the database, the problem disappear: in the admin pannel, i got "fr" in "code" and "French" in "name.
It seems there is a bug in the method to create locale in admin panel that put the name instead of the code in the code attribute of locale.

**Comment by pjedrzejewski** [comment]
I reproduced this locally and it seems like Symfony changed the ``locale`` type in 2.8. It is the other way around, uses locale name as value and code as label. While on Symfony 2.7.7 it is the opposite.

Thanks for reporting!

**Comment by michalmarcinkowski** [comment]
Should be fixed.
