### ISSUE TITLE
How to integrate full Sylius testing in continuous integration process

### ISSUE THREAD

**Issue by nicodmf** [Sylius/Sylius-Standard#88]
Hello,

To begin, thanks for this great project, very usefull and malleable.

So, my question is the same than in the title : 

How can i integrate the full Sylius test suites from the standard edition ?

Best Regards,

Nicolas

**Comment by pjedrzejewski** [comment]
@nicodmf This is something we are exploring right now too, especially that we have page objects in new Behat suites - which allows us to easily customize tests to work with various interfaces. I hope to take a look at executing whole test suite in Sylius-Standard this week.

**Comment by nicodmf** [comment]
Hello, 

This will a very usefull process. I wait that with impatiently.

**Comment by pamil** [comment]
@nicodmf there's #98 incoming in the near future with ability to run Sylius' Behat tests OOTB.

**Comment by michalmarcinkowski** [comment]
We run full Sylius test suite on Sylius-Standard already (https://travis-ci.org/Sylius/Sylius-Standard/builds).

**Comment by nicodmf** [comment]
Ti be exact, this is not the full test suite, but more the functionnal test suite which could be usefull. The better interest would be to know if every part of the order process (caddy, page, etc...) could be easily extended and automatcly verified.

**Comment by michalmarcinkowski** [comment]
This is something we still explore, but it should be possible ;)
