### ISSUE TITLE
Sylius e-commerce, installing & using CKeditor

### ISSUE THREAD

**Issue by bosnianmostar** [Sylius/Sylius-Standard#90]
Hello guys, I would be very thankful if somebody might help me with some stuffs about CKEditor on symfony ( sylius e-commerce project ).

Things I want to do are:

I am wondering how I could replace standard textarea on my sylius admin dashboard panel with ckeditor textarea? For example 

![bosy](https://cloud.githubusercontent.com/assets/17853339/14459296/5e91492c-00b7-11e6-9e14-be1b01ce00ee.png)

I want to replace that standard textarea with advanced text area using ck editor..

so if somebody might help me I would be really thankful.

**Comment by bosnianmostar** [comment]
solved

**Comment by nakashu** [comment]
@bosnianmostar share please, for future reference

**Comment by bosnianmostar** [comment]
If you want to include rich text editor, for example ck editor, before everything install ckeditor on your project, and after that, for example in my case I was looking to edit that body section when I want to create new content/page on sylius admin dashboard, and what you have to do is next : 

* FIND FILE StaticContentType.php ( vendor/sylius/src/sylius/bundle/contentbundle/form/type/staticcontettype.php) and after that find the place where you are adding body and its located on 65 line and looks like this ->add('body'....)

* WHEN YOU FIND THAT change whatever you see there to this : ->add('body', CKEditorType::class, [
                'required' => false,
                'label' => 'sylius.form.static_content.body',
            ])
* DONT FORGET TO INCLUDE ON THE TOP OF THE FILE
 use Ivory\CKEditorBundle\Form\Type\CKEditorType;

and that's it, you get a rich text editor instead of simple one
