### ISSUE TITLE
Not all tags are future proof

### ISSUE THREAD

**Issue by olia-bn** [Sylius/Sylius-Standard#908]
I tried installing 1.10 and 1.11 but both result in corrupted composer lock files - a conflict sneaks in via "weak" require of `sylius/paypal-plugin: ^1.2.4`

Resulting build includes both swiftmailer and symfony6 packages, hence the conflict.

Quickest fix for me was changing to `sylius/paypal-plugin: 1.2.4` (haven't tested how far the packages are actually compatibile, but original result of paypal at 1.5 was not it!).

I did see that you already tried circumvent similar situations by adding a conflict list in `sylius/sylius` but I guess as the bleeding edge moved forward, older tags in this project slipped by.

You can easily trigger it by installing  a specific project tag `composer create-project sylius/sylius-standard 1.11 acme`
I got same issue with 1.10

**Comment by jakubtobiasz** [comment]
Hello,
we checked this and `composer create-project sylius/sylius-standard:1.11 acme` uses the `1.11.0` version of the template instead of the newest one (in terms of `1.11.x`) `1.11.4`.

On the newest version, everything seems to work. However, I highly encourage you to try out the newest `1.12.x` version instead of the older one :).

**Comment by olia-bn** [comment]
> I highly encourage you to try out the newest 1.12.x version instead of the older one :)

Thanks Jakub. I personally prefer the new one but unfortunately, some of the bundles we'd like to use have not yet been made compatibile and the client would like to test their functionality.

**Comment by jakubtobiasz** [comment]
Hi @olia-bn.
In such case `composer create-project sylius/sylius-standard:1.11.4 acme` is a way for you :).

**Comment by GSadee** [comment]
Hi! I'm closing this PR, as Jakub's suggestions should help with the installation of an older version of Sylius, which is no longer maintained by us anyway.
