### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by darthmelak** [Sylius/Sylius-Standard#909]
Cloned the repository as per docker installation guide: `git clone git@github.com:Sylius/Sylius-Standard.git your_project_name`  

Upon running `docker compose up -d` it fails with the message: ```Problem 1
#0 45.82     - Root composer.json requires sylius/sylius-rector 0.11.x-dev, found sylius/sylius-rector[dev-feature/trait_helpers, dev-main, v0.11.0, 0.x-dev, v1.0, 1.0.x-dev (alias of dev-main)] but it does not match the constraint.```

**Comment by lgaitan** [comment]
I'm facing the same issue

**Comment by Rafikooo** [comment]
Hey @darthmelak,
thanks for bringing up this topic. Indeed, we overlooked it. This will be fixed ASAP ⚡

**Comment by jacquesbh** [comment]
This should be closed by #906 :)

**Comment by jakubtobiasz** [comment]
Hi,
@Rafikooo resolved this issue and I released https://github.com/Sylius/Sylius-Standard/releases/tag/v1.12.4 today :)
