### ISSUE TITLE
There are so many problems at installation!

### ISSUE THREAD

**Issue by Kharestani** [Sylius/Sylius-Standard#92]
Hi
I am new to this so maybe I am doing it wrong. when I did the following commands

1.composer create-project -s dev sylius/sylius-standard acme
2.cd acme
3.php app/console sylius:install

there was an error about system not finding the "@SyliusAdminBundle/Resources/config/grids.yml" file and it was right cause this file address was on config.yml as a resource for routing but its bundle was not installed yet. so I just commented that and planned to add it to the config file after installations are done.

then there was another error about SQL not finding the database named 'sylius_dev' which even was not the MySQL database name from the default parameters file that I choose earlier through the first installation! so I found that these names are in the cache folder and I manually cleared the cash. then there was the damn error again! so I just opened the files and change the names! and made a database on MySQL manually so it could be found! afterwards there was errors about tables and at this point I just gave up and came here to nag!

Please tell me what I need to do to make it right, I have PHP 5.5.12 running on wamp server and a count of symfony and symfony cmf programs running on this PC with no problem.

I updated my composer and what ever I thought would be the solution.

**Comment by michalmarcinkowski** [comment]
Hi @Kharestani, the first issue will be resolved by #93, but the second is more complicated and related to doctrine, but after the first install the next installation should go well without this error.

**Comment by Kharestani** [comment]
Hi @michalmarcinkowski.
Thank you for your fast response and updating the code for this Issue. You rock man!

**Comment by michalmarcinkowski** [comment]
Thank you Mohammad for reporting this! 👍
