### ISSUE TITLE
[Twig] Unknown "sylius_is_billing_address_missing" function

### ISSUE THREAD

**Issue by cavasinf** [Sylius/Sylius-Standard#926]
Fresh install from `v1.12.9`.
And following the doc: https://docs.sylius.com/en/1.12/getting-started-with-sylius/installation.html
When clicking next step on "Payment step".
This TWIG function `sylius_is_billing_address_missing` does not seem to exist:
https://github.com/Sylius/Sylius-Standard/blob/7334461483a0c4bff3edf3fbead228641ef95271/templates/bundles/SyliusShopBundle/Common/Order/_addresses.html.twig#L15-L23

**Comment by Roshyo** [comment]
I just tried, and can not reproduce.
That function is inside SyliusPaypalPlugin. Are you sure you did not disable it somehow? It would explain why the function is not found

**Comment by cavasinf** [comment]
True, we have disabled the SyliusPaypalPlugin.
It is a normal behavior then.
