### ISSUE TITLE
I can not install sylius-standard edition

### ISSUE THREAD

**Issue by folpy** [Sylius/Sylius-Standard#94]
Hi,

when I use this command:

$ composer.phar create-project sylius/sylius-standard -s dev
$ cd sylius-standard
$ app/console sylius:install

instead of standard edition sylius install dev version why?

**Comment by michalmarcinkowski** [comment]
The configuration files needs to be updated on dev version (see [my comment](https://github.com/Sylius/Sylius/issues/4984#issuecomment-217875185)). We will fix it ASAP.

**Comment by michalmarcinkowski** [comment]
Take a look at [environments](http://docs.sylius.org/en/latest/book/environments.html).

**Comment by folpy** [comment]
If I call this in terminal:

app/console --env=prod --no-debug cache:clear

then dev change to prod version right?

**Comment by pjedrzejewski** [comment]
@folpy Exactly, just like any Symfony app. Let us know if you have any further problems. :)

**Comment by folpy** [comment]
I think that we can close this thanks for help :-)
