### ISSUE TITLE
v0.17 : routing issue

### ISSUE THREAD

**Issue by remyma** [Sylius/Sylius-Standard#96]
When installing sylius-standard in version v0.17, routing.yml file tries to load sylius installer and a lot of others routing files.

But sylius installer routing.yml does not exists anymore.

```
sylius_installer:
    resource: "@SyliusInstallerBundle/Resources/config/routing.yml"
```

I see that routing changed in master, if update with this changes it is ok.
But v0.17 original routing file is not ok.

**Comment by michalmarcinkowski** [comment]
Fixed with the newest update.
