### ISSUE TITLE
Can't create a new project with composer with the newest release

### ISSUE THREAD

**Issue by patbsh** [Sylius/Sylius-Standard#976]
As described in the official docs I've tried
`composer create-project sylius/sylius-standard acme
`
During the post install cache:clear I get this:

`
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 119:
!!                                                                                 
!!    The service "sylius.fixture.order" has a dependency on a non-existent servi  
!!    ce "sylius_abstraction.state_machine".                                       
!!                                                                                 
!!  
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "JMS\SerializerBundle\JMSSerializerBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::boot()" might add "void" as a native return type declaration in the future. Do the same in child class "Knp\Bundle\GaufretteBundle\KnpGaufretteBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Sylius\Bundle\ShopBundle\SyliusShopBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "ApiPlatform\Symfony\Bundle\ApiPlatformBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "ApiPlatform\Symfony\Bundle\ApiPlatformBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::registerCommands()" might add "void" as a native return type declaration in the future. Do the same in child class "Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  2024-04-23T21:45:11+00:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "League\FlysystemBundle\FlysystemBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
!!  
Script @auto-scripts was called via post-update-cmd
`

I tried both 'classic' and docker versions.

**Comment by GSadee** [comment]
Hi @patbsh, 
I've just released the new version of Sylius-Standard with the support for Sylius 1.13. Now everything should work correctly, check if you can. 
Of course, if there are any problems, let us know 🖖🏻
