### ISSUE TITLE
I'm trying to override CartItemController

### ISSUE THREAD

**Issue by vFourcade** [Sylius/Sylius-Standard#99]
Hello All

I have a question, i have missed something

when we click on "add to cart", by default, the sylius controller redirect to cart summary
I need to display a modal to give choice :
- continue to see products
- achieve command process from cart summary

I'm following documentation : 
http://docs.sylius.org/en/latest/bundles/general/overriding_controllers.html
to override the add item action to cart

but when i write this following thing in my app/config/config.yaml :
sylius_cart:
    driver: doctrine/orm
    classes:
        cart_item:
            controller: iello\WebBundle\Controller\CartItemController

I have this exception : 
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized option "classes" under "sylius_cart"' in /Users/vincent/Documents/workspace/iello-shop/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:317 Stack trace: 
#0 /Users/vincent/Documents/workspace/iello-shop/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) 
#1 /Users/vincent/Documents/workspace/iello-shop/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(33): Symfony\Component\Config\Definition\BaseNode->normalize(Array) 
#2 /Users/vincent/Documents/workspace/iello-shop/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array)

I have set this routing param :
iello_car_item_add:
    path:     /cart/add
    defaults: { _controller: ielloWebBundle:CartItem:addAction }

I have my own controller : 
namespace iello\WebBundle\Controller;

use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Component\Cart\Event\CartItemEvent;
use Sylius\Component\Cart\Resolver\ItemResolvingException;
use Sylius\Component\Cart\SyliusCartEvents;
use Sylius\Component\Resource\Event\FlashEvent;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Component\HttpFoundation\Request;

class CartItemController extends ResourceController 
{
    public function addAction(Request $request)
    { ...

I don't see where is my mistake

I use last standard version of sylius v0.18

thanks in advance

Vincent

**Comment by vFourcade** [comment]
I found solution
I find summary.rst with "sylius_cart" définition
I override this sample configuration in my bundle

it can be added  in documention following step : 
- find the summary.rst définition
- override it
and keep your sample with ProductController

thank's, sylius rox

**Comment by pjedrzejewski** [comment]
@vFourcade Glad that you have figured it out!

**Comment by vFourcade** [comment]
I advanced some meters

my controller extends ResourceController
my controller is using

when i click on "add to cart" i have this exception : 
Catchable Fatal Error: Argument 1 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct() must implement interface Sylius\Component\Resource\Metadata\MetadataInterface, none given,

here is my stack trace

![stack](https://cloud.githubusercontent.com/assets/19576114/15574309/e2808510-234c-11e6-8c48-767a3aec3baf.png)

my crontroller is called without args :( 

what i miss in my configuration :

sylius_cart:
    resources:
        cart_item:
            classes:
                controller: iello\WebBundle\Controller\CartItemController

**Comment by michalmarcinkowski** [comment]
Fixed in the newest release.
